"use strict";

const REQUIRED_TABLES=["PROJETS","ACTIONS","CONSIGNES_POLITIQUES","ARBITRAGES_DECISIONS","AVANCEMENTS","INTERLOCUTEURS"],OPTIONAL_TABLES=["REUNIONS","JALONS","BLOCAGES","VIGILANCES","ATTENTES_EXTERNES","SERVICES"];
const CONFIG=[
 {key:"decisions",label:"Décisions",title:"Décisions actives ou à transmettre"},
 {key:"blockages",label:"Blocages",title:"Blocages actifs"},
 {key:"vigilances",label:"Vigilances",title:"Vigilances actives"},
 {key:"expectations",label:"Attentes externes",title:"Attentes externes"},
 {key:"milestones",label:"Jalons",title:"Jalons à venir"},
 {key:"actions",label:"Actions",title:"Actions ouvertes"},
 {key:"instructions",label:"Consignes",title:"Consignes actives"}
];
const state={tables:{},sections:{},enabled:Object.fromEntries(CONFIG.map(item=>[item.key,true])),hidden:new Set(),demo:false,preview:false};
const ui={loading:document.querySelector("#interface-state"),content:document.querySelector("#weekly-content"),summary:document.querySelector("#summary"),toggles:document.querySelector("#toggles"),report:document.querySelector("#report"),date:document.querySelector("#point-date"),reset:document.querySelector("#reset-hidden"),preview:document.querySelector("#preview-toggle"),print:document.querySelector("#print")};

async function initialize(){bind();ui.date.textContent=capitalize(formatDate(new Date(),true));try{state.demo=isDemoMode();state.tables=state.demo?window.POINT_HEBDO_DEMO_DATA.tables:await readGrist();state.sections=aggregate(state.tables);renderControls();render();ui.loading.hidden=true;ui.content.hidden=false}catch(error){fatal("Préparation impossible",exactError(error))}}
async function readGrist(){if(!window.grist?.docApi)throw new Error("L’API Grist n’est pas disponible. Ouvrez ce widget dans Grist ou utilisez ?demo=1.");await withTimeout(Promise.resolve(window.grist.ready({requiredAccess:"read table"})),"initialisation de l’API Grist");const available=normalizeTableNames(await withTimeout(window.grist.docApi.listTables(),"détection des tables"));const missing=REQUIRED_TABLES.filter(name=>!available.includes(name));if(missing.length)throw new Error(`Tables Grist introuvables : ${missing.join(", ")}.`);const names=[...REQUIRED_TABLES,...OPTIONAL_TABLES.filter(name=>available.includes(name))],entries=await Promise.all(names.map(async name=>[name,columnarToRecords(await withTimeout(window.grist.docApi.fetchTable(name),`lecture de ${name}`))]));return Object.fromEntries(entries)}

function aggregate(tables){const projects=tables.PROJETS||[],active=new Set(projects.filter(projectIsActive).map(row=>String(row.id))),belongs=row=>referenceIds(row.Projet||row.Projets).some(id=>active.has(id));return{decisions:(tables.ARBITRAGES_DECISIONS||[]).filter(row=>belongs(row)&&(!isDone(row.Statut)||(isTrue(row.A_transmettre)&&!isTrue(row.Transmis)))).map(row=>item("decision",row)),blockages:(tables.BLOCAGES||[]).filter(row=>belongs(row)&&isActiveObject(row,"Actif")).map(row=>item("blockage",row)),vigilances:(tables.VIGILANCES||[]).filter(row=>belongs(row)&&isActiveObject(row,"Active")).map(row=>item("vigilance",row)),expectations:(tables.ATTENTES_EXTERNES||[]).filter(row=>belongs(row)&&!isDone(row.Statut)).map(row=>item("expectation",row)),milestones:(tables.JALONS||[]).filter(row=>belongs(row)&&!isTrue(row.Franchi)).map(row=>item("milestone",row)),actions:(tables.ACTIONS||[]).filter(row=>belongs(row)&&!isDone(row.Statut)).map(row=>item("action",row)),instructions:(tables.CONSIGNES_POLITIQUES||[]).filter(row=>belongs(row)&&normalizeText(row.Statut)!=="archivee").map(row=>item("instruction",row))}}
function item(type,row,text=""){const projectIds=referenceIds(row.Projet||row.Projets);return{type,row,text,key:`${type}:${row.id??hash(JSON.stringify(row))}`,projectIds,urgency:urgencyScore(row.Statut||row.Niveau_alerte),weekly:false}}
function latestAdvancements(rows){const sorted=[...rows].sort((a,b)=>dateValue(b.Date||b.Date_MAJ)-dateValue(a.Date||a.Date_MAJ)),seen=new Set();return sorted.filter(row=>{const id=referenceIds(row.Projet)[0]||`row-${row.id}`;if(seen.has(id))return false;seen.add(id);return true})}

function renderControls(){ui.toggles.replaceChildren(...CONFIG.map(config=>{const label=element("label","toggle"),input=element("input");input.type="checkbox";input.checked=state.enabled[config.key];input.addEventListener("change",()=>{state.enabled[config.key]=input.checked;render()});label.append(input,textElement("span",config.label),textElement("small",String(state.sections[config.key].length)));return label}))}
function render(){renderSummary();const active=CONFIG.filter(config=>state.enabled[config.key]),sections=active.map(renderSection).filter(Boolean),message=active.length?"Aucun élément actif ne requiert votre attention.":"Aucune rubrique sélectionnée.";ui.report.replaceChildren(...(sections.length?sections:[textElement("p",message,"empty-section")]));ui.reset.hidden=state.hidden.size===0}
function renderSummary(){ui.summary.replaceChildren(...CONFIG.map(config=>{const count=visibleItems(config.key).length,card=element("article",`summary-card${count===0?" summary-card--empty":""}`);card.append(textElement("strong",String(count)),textElement("span",config.label));return card}))}
function renderSection(config){const rows=visibleItems(config.key).sort(compareItems);if(!rows.length)return null;const section=element("section","report-section"),heading=element("div","section-heading");heading.append(textElement("h2",config.title),textElement("span",`${rows.length} élément${rows.length>1?"s":""}`));section.append(heading);groupByProject(rows).forEach(group=>{const wrapper=element("div","project-group");wrapper.append(textElement("h3",group.name,"project-group__title"));const list=element("div","items");list.append(...group.items.map(renderCard));wrapper.append(list);section.append(wrapper)});return section}
function renderCard(itemData){const {row,type,key}=itemData,card=element("article",`report-card report-card--${cardTone(itemData)}`),top=element("div","report-card__top"),titleBox=element("div");titleBox.append(textElement("h4",itemTitle(itemData)));const meta=element("div","report-card__meta");meta.append(...itemBadges(itemData));titleBox.append(meta);const hide=textElement("button","Masquer","hide-item no-print");hide.type="button";hide.title="Retirer de cette synthèse (réversible)";hide.setAttribute("aria-label",`Retirer ${itemTitle(itemData)} de cette synthèse`);hide.addEventListener("click",()=>{state.hidden.add(key);render()});top.append(titleBox,hide);card.append(top);const body=element("div","report-card__body");fieldsFor(type,row,itemData.text).forEach(([label,value])=>{if(hasValue(value)){const p=element("p");p.append(textElement("span",label,"field-label"),document.createTextNode(displayValue(value)));body.append(p)}});if(body.children.length)card.append(body);return card}
function fieldsFor(type,row,text){if(type==="decision")return[["Question à trancher",row.Question_a_trancher],["Contexte",row.Contexte],["Décision",row.Decision_prise||row.Decision],["Date nécessaire",formatDate(row.Echeance_decision)]];if(type==="blockage")return[["Depuis",formatDate(row.Date_apparition)],["Résolution",row.Explication_resolution]];if(type==="vigilance")return[["Depuis",formatDate(row.Date_apparition)],["Détail",row.Description]];if(type==="expectation")return[["Tiers",personName(row.Tiers)],["Date attendue",formatDate(row.Date_attendue)]];if(type==="milestone")return[["Ordre",row.Ordre],["Date prévue",formatDate(row.Date_prevue)]];if(type==="instruction")return[["Émetteur",personName(row.Emetteur)],["Destinataires",personName(row.Destinataires||row.Responsable)]];if(type==="action")return[["Attribuée à",personName(row.Attribuee_a||row.Responsable)],["Échéance",formatDate(row.Echeance)]];return[["À retenir",text]]}
function itemTitle({type,row,text}){return textOr(type==="decision"?row.Sujet||row.Question_a_trancher:type==="blockage"?row.Blocage:type==="vigilance"?row.Vigilance:type==="expectation"?row.Attente:type==="milestone"?row.Jalon:type==="instruction"?row.Consigne:type==="action"?row.Action:text,"Élément sans titre")}
function itemBadges({row,type}){const values=[];if(hasValue(row.Niveau_alerte))values.push(badge(row.Niveau_alerte,badgeTone(row.Niveau_alerte)));if(hasValue(row.Statut)&&type!=="priority")values.push(badge(row.Statut,"info"));const due=row.Echeance_decision||row.Echeance||row.Date_echeance;if(hasValue(due))values.push(badge(formatDate(due),dateValue(due)<startOfDay(new Date())?"danger":"warning"));return values}
function visibleItems(key){return(state.sections[key]||[]).filter(row=>!state.hidden.has(row.key))}
function groupByProject(items){const groups=new Map();items.forEach(entry=>{const ids=entry.projectIds.length?entry.projectIds:["none"];ids.forEach(id=>{const name=id==="none"?(entry.type==="priority"?textOr(entry.row.Nom_projet,"Projet non renseigné"):"Sans projet"):projectName(id);if(!groups.has(name))groups.set(name,[]);groups.get(name).push(entry)})});return[...groups.entries()].sort(([a],[b])=>a.localeCompare(b,"fr")).map(([name,groupItems])=>({name,items:groupItems.sort(compareItems)}))}
function compareItems(a,b){return b.urgency-a.urgency||(dateValue(a.row.Echeance_decision||a.row.Echeance||a.row.Date_attendue||a.row.Date_prevue)||Infinity)-(dateValue(b.row.Echeance_decision||b.row.Echeance||b.row.Date_attendue||b.row.Date_prevue)||Infinity)||itemTitle(a).localeCompare(itemTitle(b),"fr")}

function bind(){ui.print.addEventListener("click",()=>window.print());ui.preview.addEventListener("click",()=>{state.preview=!state.preview;document.body.classList.toggle("meeting-preview",state.preview);ui.preview.setAttribute("aria-pressed",String(state.preview));ui.preview.textContent=state.preview?"Quitter l’aperçu":"Aperçu imprimable"});ui.reset.addEventListener("click",()=>{state.hidden.clear();render()})}
function projectIsActive(row){return window.PilotageV3Rules?.isProjectActive(row)??!["termine","abandonne"].includes(normalizeText(row.Statut))}function isActiveObject(row,field){return !(field in row)||isTrue(row[field])}
function isDone(value){const text=normalizeText(value);return["realise","termine","clos","annule","non about","valide","transmis","decidee","decide","prise","sans suite","archive"].some(word=>text.includes(word))}function urgencyScore(value){return /bloc|retard/.test(normalizeText(value))?3:0}function cardTone(itemData){if(itemData.type==="decision")return"arbitration";if(itemData.type==="blockage")return"critical";if(itemData.type==="vigilance")return"high";return itemData.urgency>=3?"critical":"info"}function badgeTone(value){return urgencyScore(value)>=3?"danger":"info"}
function projectName(id){const project=(state.tables.PROJETS||[]).find(row=>String(row.id)===String(id));return project?textOr(project.Nom_projet,"Projet sans nom"):"Projet inconnu"}function personName(value){const names=referenceIds(value).map(id=>{const row=(state.tables.INTERLOCUTEURS||[]).find(person=>String(person.id)===id);return row?textOr(row.Nom_complet||[row.Prenom,row.Nom].filter(hasValue).join(" "),"Interlocuteur sans nom"):"Non renseigné"});return[...new Set(names)].filter(name=>name!=="Non renseigné").join(", ")||"Non renseigné"}
function normalizeTableNames(value){const rows=Array.isArray(value)?value:Array.isArray(value?.tables)?value.tables:[];return rows.map(row=>typeof row==="string"?row:row?.id??row?.tableId??row?.name??"").filter(Boolean)}function columnarToRecords(columns){const names=Object.keys(columns||{}).filter(name=>Array.isArray(columns[name])),length=Math.max(0,...names.map(name=>columns[name].length));return Array.from({length},(_,index)=>Object.fromEntries(names.map(name=>[name,columns[name][index]])))}function referenceIds(value){return[...new Set((Array.isArray(value)?value:[value]).filter(item=>item!=="L"&&item!==0&&item!=="0"&&hasValue(item)).map(String))]}function withTimeout(promise,label,delay=12000){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(`Délai dépassé pendant : ${label}.`)),delay))])}function isDemoMode(){return window.self===window.top&&new URLSearchParams(location.search).get("demo")==="1"&&Boolean(window.POINT_HEBDO_DEMO_DATA)}function fatal(title,message){ui.content.hidden=true;ui.loading.replaceChildren(textElement("strong",title),textElement("p",message));ui.loading.hidden=false}function dateValue(value){if(!hasValue(value))return 0;const date=value instanceof Date?value:new Date(typeof value==="number"?value*1000:value);return Number.isNaN(date.getTime())?0:date.getTime()}function startOfDay(date){return new Date(date.getFullYear(),date.getMonth(),date.getDate()).getTime()}function formatDate(value,withWeekday=false){const time=dateValue(value);return time?new Intl.DateTimeFormat("fr-FR",{weekday:withWeekday?"long":undefined,day:"numeric",month:"long",year:"numeric"}).format(new Date(time)):""}function hasValue(value){return value!==null&&value!==undefined&&String(value).trim()!==""}function displayValue(value){if(Array.isArray(value))return value.filter(item=>item!=="L").map(displayValue).join(", ");return hasValue(value)?String(value).trim():""}function textOr(value,fallback){return hasValue(value)?displayValue(value):fallback}function normalizeText(value){return displayValue(value).toLocaleLowerCase("fr-FR").normalize("NFD").replace(/[\u0300-\u036f]/g,"")}function isTrue(value){return value===true||value===1||["true","vrai","oui","1"].includes(normalizeText(value))}function exactError(error){return error instanceof Error?error.message:String(error)}function capitalize(value){return value?value[0].toLocaleUpperCase("fr-FR")+value.slice(1):value}function hash(value){let result=0;for(let index=0;index<value.length;index++)result=(result*31+value.charCodeAt(index))|0;return Math.abs(result)}function element(tag,className){const node=document.createElement(tag);if(className)node.className=className;return node}function textElement(tag,value,className){const node=element(tag,className);node.textContent=displayValue(value);return node}function badge(value,tone){return textElement("span",value,`badge badge--${tone}`)}
initialize();
