"use strict";

const TABLES=["PROJETS","REUNIONS","ACTIONS","CONSIGNES_POLITIQUES","ARBITRAGES_DECISIONS","AVANCEMENTS","INTERLOCUTEURS"];
const CONFIG=[
 {key:"openDecisions",label:"Décisions à prendre",title:"Décisions à prendre"},
 {key:"vigilance",label:"Points de vigilance",title:"Points de vigilance"},
 {key:"instructions",label:"Consignes à contrôler",title:"Consignes à contrôler"},
 {key:"lateActions",label:"Actions en retard",title:"Actions en retard / à relancer"},
 {key:"decisions",label:"Décisions à transmettre",title:"Décisions récentes / à transmettre"},
 {key:"priorityProjects",label:"Projets prioritaires",title:"Projets prioritaires"},
 {key:"meetings",label:"Dernières réunions",title:"Réunions récentes"}
];
const state={tables:{},sections:{},enabled:Object.fromEntries(CONFIG.map(item=>[item.key,true])),hidden:new Set(),demo:false,preview:false};
const ui={loading:document.querySelector("#interface-state"),content:document.querySelector("#weekly-content"),summary:document.querySelector("#summary"),toggles:document.querySelector("#toggles"),report:document.querySelector("#report"),date:document.querySelector("#point-date"),reset:document.querySelector("#reset-hidden"),preview:document.querySelector("#preview-toggle"),print:document.querySelector("#print")};

async function initialize(){bind();ui.date.textContent=capitalize(formatDate(new Date(),true));try{state.demo=isDemoMode();state.tables=state.demo?window.POINT_HEBDO_DEMO_DATA.tables:await readGrist();state.sections=aggregate(state.tables);renderControls();render();ui.loading.hidden=true;ui.content.hidden=false}catch(error){fatal("Préparation impossible",exactError(error))}}
async function readGrist(){if(!window.grist?.docApi)throw new Error("L’API Grist n’est pas disponible. Ouvrez ce widget dans Grist ou utilisez ?demo=1.");await withTimeout(Promise.resolve(window.grist.ready({requiredAccess:"read table"})),"initialisation de l’API Grist");const available=normalizeTableNames(await withTimeout(window.grist.docApi.listTables(),"détection des tables"));const missing=TABLES.filter(name=>!available.includes(name));if(missing.length)throw new Error(`Tables Grist introuvables : ${missing.join(", ")}.`);const entries=await Promise.all(TABLES.map(async name=>[name,columnarToRecords(await withTimeout(window.grist.docApi.fetchTable(name),`lecture de ${name}`))]));return Object.fromEntries(entries)}

function aggregate(tables){const now=startOfDay(new Date()),projects=tables.PROJETS||[],advancements=tables.AVANCEMENTS||[],decisionRows=tables.ARBITRAGES_DECISIONS||[],openDecisions=decisionRows.filter(isOpenDecision);const vigilance=[...projects.filter(hasProjectWarning).map(row=>item("project",row,row.Point_vigilance||row.Points_vigilance||row.Blocage||row.Risques||row.Description)),...latestAdvancements(advancements).filter(hasAdvancementWarning).map(row=>item("advancement",row,row.Point_vigilance||row.Alerte||row.Avancement))];const instructions=(tables.CONSIGNES_POLITIQUES||[]).filter(row=>!isDone(row.Statut)&&!isTrue(row.Controle_elu)).map(row=>item("instruction",row));const lateActions=(tables.ACTIONS||[]).filter(row=>!isDone(row.Statut)&&dateValue(row.Echeance||row.Date_echeance)>0&&dateValue(row.Echeance||row.Date_echeance)<now).map(row=>item("action",row));const decisions=decisionRows.filter(row=>(isDecided(row)&&isRecent(row.Date_decision||row.Date_MAJ||row.Date,21))||(isTrue(row.A_transmettre)&&!isTrue(row.Transmis))).map(row=>item("decision",row));const priorityProjects=projects.filter(row=>isPriority(row.Priorite||row.Urgence)||isBlocked(row.Statut)).map(row=>item("priority",row));const meetings=(tables.REUNIONS||[]).filter(row=>isRecent(row.Date_reunion||row.Date,21)&&hasMeetingOutput(row)).map(row=>item("meeting",row));return{openDecisions:openDecisions.map(row=>item("openDecision",row)),vigilance,instructions,lateActions,decisions,priorityProjects,meetings}}
function item(type,row,text=""){const projectIds=type==="project"||type==="priority"?[String(row.id)]:referenceIds(row.Projet||row.Projets);return{type,row,text,key:`${type}:${row.id??hash(JSON.stringify(row))}`,projectIds,urgency:urgencyScore(row.Urgence||row.Priorite||row.Niveau_alerte||row.Statut),weekly:isTrue(row.Point_hebdo)}}
function latestAdvancements(rows){const sorted=[...rows].sort((a,b)=>dateValue(b.Date||b.Date_MAJ)-dateValue(a.Date||a.Date_MAJ)),seen=new Set();return sorted.filter(row=>{const id=referenceIds(row.Projet)[0]||`row-${row.id}`;if(seen.has(id))return false;seen.add(id);return true})}

function renderControls(){ui.toggles.replaceChildren(...CONFIG.map(config=>{const label=element("label","toggle"),input=element("input");input.type="checkbox";input.checked=state.enabled[config.key];input.addEventListener("change",()=>{state.enabled[config.key]=input.checked;render()});label.append(input,textElement("span",config.label),textElement("small",String(state.sections[config.key].length)));return label}))}
function render(){renderSummary();const active=CONFIG.filter(config=>state.enabled[config.key]),sections=active.map(renderSection).filter(Boolean),message=active.length?"Aucun élément ne correspond aux critères du point hebdomadaire.":"Aucune rubrique sélectionnée.";ui.report.replaceChildren(...(sections.length?sections:[textElement("p",message,"empty-section")]));ui.reset.hidden=state.hidden.size===0}
function renderSummary(){ui.summary.replaceChildren(...CONFIG.map(config=>{const count=visibleItems(config.key).length,card=element("article","summary-card");card.append(textElement("strong",String(count)),textElement("span",config.label));return card}))}
function renderSection(config){const rows=visibleItems(config.key).sort(compareItems);if(!rows.length)return null;const section=element("section","report-section"),heading=element("div","section-heading");heading.append(textElement("h2",config.title),textElement("span",`${rows.length} élément${rows.length>1?"s":""}`));section.append(heading);groupByProject(rows).forEach(group=>{const wrapper=element("div","project-group");wrapper.append(textElement("h3",group.name,"project-group__title"));const list=element("div","items");list.append(...group.items.map(renderCard));wrapper.append(list);section.append(wrapper)});return section}
function renderCard(itemData){const {row,type,key}=itemData,card=element("article",`report-card report-card--${cardTone(itemData)}`),top=element("div","report-card__top"),titleBox=element("div");titleBox.append(textElement("h4",itemTitle(itemData)));const meta=element("div","report-card__meta");meta.append(...itemBadges(itemData));titleBox.append(meta);const hide=textElement("button","×","hide-item no-print");hide.type="button";hide.title="Masquer pour cette session";hide.setAttribute("aria-label",`Masquer ${itemTitle(itemData)}`);hide.addEventListener("click",()=>{state.hidden.add(key);render()});top.append(titleBox,hide);card.append(top);const body=element("div","report-card__body");fieldsFor(type,row,itemData.text).forEach(([label,value])=>{if(hasValue(value)){const p=element("p");p.append(textElement("span",label,"field-label"),document.createTextNode(displayValue(value)));body.append(p)}});if(body.children.length)card.append(body);return card}
function fieldsFor(type,row,text){if(type==="openDecision")return[["Contexte",row.Contexte],["Question à trancher",row.Question_a_trancher],["Options",row.Options],["Position élue",row.Position_elue],["Échéance",formatDate(row.Echeance_decision)]];if(type==="decision")return[["Décision",row.Decision||row.Decision_prise||row.Position_elue],["Contexte",row.Contexte],["Date",formatDate(row.Date_decision||row.Date)]];if(type==="instruction")return[["Responsable",personName(row.Responsable)],["Échéance",formatDate(row.Echeance||row.Date_echeance)],["Retour / contrôle",row.Retour_service||row.Commentaire]];if(type==="action")return[["Responsable",personName(row.Responsable)],["Échéance",formatDate(row.Echeance||row.Date_echeance)],["Suivi",row.Commentaire||row.Resultat]];if(type==="meeting")return[["Date",formatDate(row.Date_reunion||row.Date)],["Points clés",row.Points_cles||row.Compte_rendu],["Décisions",row.Decisions_prises||row.Decision],["Actions / engagements",row.Actions||row.Engagements],["Décision à prendre",row.Arbitrage_attendu||row.Arbitrage||row.Arbitrages]];if(type==="priority")return[["Statut",row.Statut],["Vigilance",row.Point_vigilance||row.Points_vigilance||row.Blocage||row.Risques],["Prochaine étape",row.Prochaine_etape]];return[["À retenir",text],["Dernière mise à jour",formatDate(row.Date||row.Date_MAJ)]]}
function itemTitle({type,row,text}){return textOr(type==="openDecision"||type==="decision"?row.Sujet:type==="instruction"?row.Consigne:type==="action"?row.Action:type==="meeting"?row.Objet:type==="priority"?row.Nom_projet:text,"Élément sans titre")}
function itemBadges({row,type}){const values=[];if(hasValue(row.Urgence||row.Priorite||row.Niveau_alerte))values.push(badge(row.Urgence||row.Priorite||row.Niveau_alerte,badgeTone(row.Urgence||row.Priorite||row.Niveau_alerte)));if(hasValue(row.Statut)&&type!=="priority")values.push(badge(row.Statut,"info"));const due=row.Echeance_decision||row.Echeance||row.Date_echeance;if(hasValue(due))values.push(badge(formatDate(due),dateValue(due)<startOfDay(new Date())?"danger":"warning"));return values}
function visibleItems(key){return(state.sections[key]||[]).filter(row=>!state.hidden.has(row.key))}
function groupByProject(items){const groups=new Map();items.forEach(entry=>{const ids=entry.projectIds.length?entry.projectIds:["none"];ids.forEach(id=>{const name=id==="none"?(entry.type==="priority"?textOr(entry.row.Nom_projet,"Projet non renseigné"):"Sans projet"):projectName(id);if(!groups.has(name))groups.set(name,[]);groups.get(name).push(entry)})});return[...groups.entries()].sort(([a],[b])=>a.localeCompare(b,"fr")).map(([name,groupItems])=>({name,items:groupItems.sort(compareItems)}))}
function compareItems(a,b){return Number(b.weekly)-Number(a.weekly)||b.urgency-a.urgency||dateValue(a.row.Echeance_decision)-dateValue(b.row.Echeance_decision)||itemTitle(a).localeCompare(itemTitle(b),"fr")}

function bind(){ui.print.addEventListener("click",()=>window.print());ui.preview.addEventListener("click",()=>{state.preview=!state.preview;document.body.classList.toggle("meeting-preview",state.preview);ui.preview.setAttribute("aria-pressed",String(state.preview));ui.preview.textContent=state.preview?"Quitter l’aperçu":"Aperçu réunion"});ui.reset.addEventListener("click",()=>{state.hidden.clear();render()})}
function hasProjectWarning(row){return hasValue(row.Point_vigilance||row.Points_vigilance||row.Blocage||row.Risques)||isBlocked(row.Statut)}function hasAdvancementWarning(row){return hasValue(row.Point_vigilance||row.Alerte)||urgencyScore(row.Niveau_alerte)>=2}function isOpenDecision(row){return["a preparer","a decider","reportee"].includes(normalizeText(row.Statut))}function isDecided(row){return["decidee","decide"].includes(normalizeText(row.Statut))}function hasMeetingOutput(row){return["Arbitrage_attendu","Arbitrage","Arbitrages","Decisions_prises","Decision","Actions","Engagements"].some(key=>hasValue(row[key]))}function isPriority(value){return urgencyScore(value)>=2}function isBlocked(value){return normalizeText(value).includes("bloqu")||normalizeText(value).includes("alerte")}function isDone(value){const text=normalizeText(value);return["realise","termine","clos","annule","valide","transmis","decidee","decide","sans suite"].some(word=>text.includes(word))}function isRecent(value,days){const time=dateValue(value);return time>0&&time>=Date.now()-days*86400000}function urgencyScore(value){const text=normalizeText(value);if(/critique|urgent|bloc|retard/.test(text))return 3;if(/haute|elevee|orange|prioritaire/.test(text))return 2;if(/normale|moyenne|jaune/.test(text))return 1;return 0}function cardTone(itemData){if(itemData.type==="openDecision"||itemData.type==="decision")return"arbitration";return itemData.urgency>=3?"critical":itemData.urgency>=2?"high":"info"}function badgeTone(value){const score=urgencyScore(value);return score>=3?"danger":score>=2?"warning":"info"}
function projectName(id){return textOr((state.tables.PROJETS||[]).find(row=>String(row.id)===String(id))?.Nom_projet,"Projet inconnu")}function personName(value){const names=referenceIds(value).map(id=>{const row=(state.tables.INTERLOCUTEURS||[]).find(person=>String(person.id)===id);return row?textOr(row.Nom_complet||[row.Prenom,row.Nom].filter(hasValue).join(" "),"Interlocuteur"):"Interlocuteur inconnu"});return names.join(", ")||"Non renseigné"}
function normalizeTableNames(value){const rows=Array.isArray(value)?value:Array.isArray(value?.tables)?value.tables:[];return rows.map(row=>typeof row==="string"?row:row?.id??row?.tableId??row?.name??"").filter(Boolean)}function columnarToRecords(columns){const names=Object.keys(columns||{}).filter(name=>Array.isArray(columns[name])),length=Math.max(0,...names.map(name=>columns[name].length));return Array.from({length},(_,index)=>Object.fromEntries(names.map(name=>[name,columns[name][index]])))}function referenceIds(value){return[...new Set((Array.isArray(value)?value:[value]).filter(item=>item!=="L"&&hasValue(item)).map(String))]}function withTimeout(promise,label,delay=12000){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(`Délai dépassé pendant : ${label}.`)),delay))])}function isDemoMode(){return window.self===window.top&&new URLSearchParams(location.search).get("demo")==="1"&&Boolean(window.POINT_HEBDO_DEMO_DATA)}function fatal(title,message){ui.content.hidden=true;ui.loading.replaceChildren(textElement("strong",title),textElement("p",message));ui.loading.hidden=false}function dateValue(value){if(!hasValue(value))return 0;const date=value instanceof Date?value:new Date(typeof value==="number"?value*1000:value);return Number.isNaN(date.getTime())?0:date.getTime()}function startOfDay(date){return new Date(date.getFullYear(),date.getMonth(),date.getDate()).getTime()}function formatDate(value,withWeekday=false){const time=dateValue(value);return time?new Intl.DateTimeFormat("fr-FR",{weekday:withWeekday?"long":undefined,day:"numeric",month:"long",year:"numeric"}).format(new Date(time)):""}function hasValue(value){return value!==null&&value!==undefined&&String(value).trim()!==""}function displayValue(value){if(Array.isArray(value))return value.filter(item=>item!=="L").map(displayValue).join(", ");return hasValue(value)?String(value).trim():""}function textOr(value,fallback){return hasValue(value)?displayValue(value):fallback}function normalizeText(value){return displayValue(value).toLocaleLowerCase("fr-FR").normalize("NFD").replace(/[\u0300-\u036f]/g,"")}function isTrue(value){return value===true||value===1||["true","vrai","oui","1"].includes(normalizeText(value))}function exactError(error){return error instanceof Error?error.message:String(error)}function capitalize(value){return value?value[0].toLocaleUpperCase("fr-FR")+value.slice(1):value}function hash(value){let result=0;for(let index=0;index<value.length;index++)result=(result*31+value.charCodeAt(index))|0;return Math.abs(result)}function element(tag,className){const node=document.createElement(tag);if(className)node.className=className;return node}function textElement(tag,value,className){const node=element(tag,className);node.textContent=displayValue(value);return node}function badge(value,tone){return textElement("span",value,`badge badge--${tone}`)}
initialize();
