"use strict";
window.POINT_HEBDO_DEMO_DATA={tables:{
PROJETS:[{id:1,Nom_projet:"Réaménagement du centre-bourg",Statut:"En cours",Priorite:"Haute",Point_vigilance:"Décalage possible du calendrier de voirie",Actif:true},{id:2,Nom_projet:"Maison de santé",Statut:"Bloqué",Priorite:"Critique",Point_vigilance:"Accord foncier à sécuriser avant vendredi",Actif:true},{id:3,Nom_projet:"Plan vélo",Statut:"En cours",Priorite:"Normale",Actif:true}],
INTERLOCUTEURS:[{id:1,Nom_complet:"Claire Martin"},{id:2,Nom_complet:"Julien Robert"},{id:3,Nom_complet:"Sophie Bernard"}],
ARBITRAGES_DECISIONS:[{id:1,Projet:2,Sujet:"Choix du terrain",Contexte:"Deux emprises restent possibles.",Question_a_trancher:"Valider l'emprise nord ou l'emprise gare ?",Options:"Nord : acquisition rapide\nGare : meilleure desserte",Position_elue:"Privilégier l'accès aux transports",Urgence:"Critique",Echeance_decision:"2026-08-28",Statut:"À décider",Point_hebdo:true,A_transmettre:false,Transmis:false},{id:2,Projet:1,Sujet:"Phasage des travaux",Contexte:"Le marché a été attribué.",Question_a_trancher:"Maintenir les travaux pendant le marché de Noël ?",Options:"Pause complète / circulation alternée",Urgence:"Haute",Echeance_decision:"2026-09-02",Statut:"En attente",Point_hebdo:true,A_transmettre:false,Transmis:false},{id:3,Projet:3,Sujet:"Stationnement avenue du Lac",Contexte:"Décision prise en comité.",Decision:"Maintien de huit places avec bande cyclable protégée.",Urgence:"Normale",Date_decision:"2026-08-24",Statut:"Décidé",A_transmettre:true,Transmis:false}],
CONSIGNES_POLITIQUES:[{id:1,Projet:1,Consigne:"Présenter un planning riverains détaillé",Responsable:1,Statut:"À contrôler",Echeance:"2026-08-29",Controle_elu:false,Priorite:"Haute"},{id:2,Projet:3,Consigne:"Vérifier la desserte du collège",Responsable:3,Statut:"En cours",Echeance:"2026-09-04",Controle_elu:true}],
ACTIONS:[{id:1,Projet:2,Action:"Obtenir l'estimation des Domaines",Responsable:2,Statut:"En cours",Echeance:"2026-08-22",Priorite:"Haute"},{id:2,Projet:1,Action:"Transmettre le plan de déviation",Responsable:1,Statut:"À faire",Echeance:"2026-08-25",Priorite:"Normale"},{id:3,Projet:3,Action:"Consulter l'association vélo",Responsable:3,Statut:"Réalisée",Echeance:"2026-08-20"}],
AVANCEMENTS:[{id:1,Projet:2,Date:"2026-08-25",Avancement:"Le propriétaire demande une nouvelle rencontre.",Point_vigilance:"Négociation foncière non finalisée",Niveau_alerte:"Critique"},{id:2,Projet:1,Date:"2026-08-24",Avancement:"Le planning travaux a été recalé.",Niveau_alerte:"Orange"}],
REUNIONS:[{id:1,Projet:2,Date_reunion:"2026-08-25",Objet:"Comité de pilotage foncier",Points_cles:"Comparaison des deux terrains et contraintes d'accès.",Decisions_prises:"Demander une estimation complémentaire.",Actions:"Relance des Domaines",Arbitrage:"Choix définitif du terrain",Participants:["L",1,2]},{id:2,Projet:1,Date_reunion:"2026-08-21",Objet:"Réunion chantier",Points_cles:"Organisation des travaux et accès commerces.",Engagements:"Informer chaque commerce avant le démarrage.",Participants:["L",1]}]
}};
