"use strict";
window.POINT_HEBDO_DEMO_DATA={tables:{
PROJETS:[{id:1,Nom_projet:"Réaménagement du centre-bourg",Statut:"En cours",Actif:true},{id:2,Nom_projet:"Maison de santé",Statut:"En cours",Actif:true},{id:3,Nom_projet:"Plan vélo",Statut:"En cours",Actif:true}],
INTERLOCUTEURS:[{id:1,Nom_complet:"Claire Martin"},{id:2,Nom_complet:"Julien Robert"},{id:3,Nom_complet:"Sophie Bernard"}],
ARBITRAGES_DECISIONS:[{id:1,Projet:2,Sujet:"Choix du terrain",Contexte:"Deux emprises restent possibles.",Question_a_trancher:"Valider l'emprise nord ou l'emprise gare ?",Options:"Nord : acquisition rapide\nGare : meilleure desserte",Position_elue:"Privilégier l'accès aux transports",Urgence:"Critique",Echeance_decision:"2026-08-28",Statut:"Demandée",A_transmettre:false,Transmis:false},{id:2,Projet:1,Sujet:"Phasage des travaux",Contexte:"Le marché a été attribué.",Question_a_trancher:"Maintenir les travaux pendant le marché de Noël ?",Options:"Pause complète / circulation alternée",Urgence:"Haute",Echeance_decision:"2026-09-02",Statut:"En instruction",A_transmettre:false,Transmis:false},{id:3,Projet:3,Sujet:"Stationnement avenue du Lac",Contexte:"Décision prise en comité.",Decision_prise:"Maintien de huit places avec bande cyclable protégée.",Urgence:"Normale",Date_decision:"2026-08-24",Statut:"Prise",A_transmettre:true,Transmis:false}],
ACTIONS:[{id:1,Projet:2,Action:"Obtenir l'estimation des Domaines",Attribuee_a:2,Statut:"En cours",Echeance:"2026-08-22"},{id:2,Projet:1,Action:"Transmettre le plan de déviation",Attribuee_a:1,Statut:"À faire",Echeance:"2026-08-25"},{id:3,Projet:3,Action:"Consulter l'association vélo",Attribuee_a:3,Statut:"Réalisée",Echeance:"2026-08-20"}],
AVANCEMENTS:[{id:1,Projet:2,Date_MAJ:"2026-08-25",Type_entree:"Information",Contenu:"Le propriétaire demande une nouvelle rencontre."},{id:2,Projet:1,Date_MAJ:"2026-08-24",Type_entree:"Avancement",Contenu:"Le planning travaux a été recalé."}],
BLOCAGES:[{id:1,Projet:2,Blocage:"Négociation foncière non finalisée",Actif:true,Date_apparition:"2026-08-25"}],
VIGILANCES:[{id:1,Projet:1,Vigilance:"Décalage possible du calendrier de voirie",Active:true,Date_apparition:"2026-08-24"}],
REUNIONS:[{id:1,Projet:2,Date_reunion:"2026-08-25",Objet:"Comité de pilotage foncier",Points_cles:"Comparaison des deux terrains et contraintes d'accès.",Compte_rendu:"Une estimation complémentaire sera demandée aux Domaines.",Participants:["L",1,2]},{id:2,Projet:1,Date_reunion:"2026-08-21",Objet:"Réunion chantier",Points_cles:"Organisation des travaux et accès commerces.",Compte_rendu:"Chaque commerce sera informé avant le démarrage.",Participants:["L",1]}]
}};
