"use strict";
const REQUIRED_TABLES=["PROJETS","REUNIONS","INTERLOCUTEURS"],OPTIONAL_TABLES=["REUNIONS_VERSIONS"];
const AGENDA_COLUMNS=["Ordre_du_jour","Ordre_jour","Agenda","Points_cles"];
const PROJECT_PEOPLE=["Responsable","Agent_pilote","Elu_pilote","Interlocuteurs","Membres","Membres_projet","Equipe_projet","Partenaires"];
const state={project:null,projects:[],meetings:[],people:[],tables:{},writable:null,columnMeta:{},tableNames:[],currentUser:null,filter:"all",search:"",demo:false,editing:null,participantIds:[],showAllPeople:false,participantSearch:"",versionMeeting:null,busy:false};
const $=s=>document.querySelector(s),ui={state:$("#interface-state"),content:$("#meetings-content"),projectName:$("#project-name"),projectSelector:$("#project-selector"),total:$("#meeting-count"),kpis:$("#meeting-kpis"),filters:$("#filter-list"),search:$("#meeting-search"),results:$("#results-count"),list:$("#meeting-list"),template:$("#meeting-template"),newMeeting:$("#new-meeting"),meetingDialog:$("#meeting-dialog"),meetingForm:$("#meeting-form"),meetingGeneral:$("#meeting-general-fields"),meetingAgenda:$("#meeting-agenda-fields"),meetingParticipants:$("#meeting-participant-fields"),meetingReport:$("#meeting-report-fields"),meetingSubmit:$("#meeting-submit"),versionDialog:$("#version-dialog"),versionForm:$("#version-form"),versionFields:$("#version-fields"),versionContext:$("#version-context"),feedback:$("#feedback")};

async function initialize(){bindControls();try{if(isDemo()){state.demo=true;state.tableNames=[...REQUIRED_TABLES,...OPTIONAL_TABLES];applyData(window.MEETINGS_DEMO_DATA.project,window.MEETINGS_DEMO_DATA.tables,window.MEETINGS_DEMO_DATA.columnMeta);state.currentUser={personId:state.people[0]?.id};return}if(!window.grist?.docApi)throw Error("L’API Grist n’est pas disponible.");await timeout(Promise.resolve(window.grist.ready({requiredAccess:"full"})),"initialisation de Grist");state.tableNames=normalizeTableNames(await timeout(window.grist.docApi.listTables(),"détection des tables"));const missing=REQUIRED_TABLES.filter(n=>!state.tableNames.includes(n));if(missing.length)throw Error(`Tables Grist introuvables : ${missing.join(", ")}.`);const names=availableTables();state.tables=await fetchTables(names);await fetchSchema(names);sync();try{state.currentUser=await timeout(window.PilotageCurrentUser.identify({people:state.people}),"identification de l’auteur")}catch(error){console.warn(error)}populateProjects();state.project=firstProject();window.grist.onRecord(record=>{const p=record&&state.projects.find(row=>same(row.id,record.id));if(p){state.project=p;render()}});render()}catch(error){console.error(error);showState("Connexion à Grist impossible",exactError(error))}}
const availableTables=()=>[...REQUIRED_TABLES,...OPTIONAL_TABLES.filter(n=>state.tableNames.includes(n))];
async function fetchTables(names){return Object.fromEntries(await Promise.all(names.map(async n=>[n,columnar(await timeout(window.grist.docApi.fetchTable(n),`lecture de ${n}`))])))}
function timeout(p,label,delay=10000){return Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(Error(`Délai dépassé pendant : ${label}.`)),delay))])}
function applyData(project,tables,columnMeta={}){state.tables=tables;state.writable=Object.fromEntries(Object.entries(tables).map(([n,rows])=>[n,new Set([...rows.flatMap(Object.keys),...Object.keys(columnMeta[n]||{})])]));state.columnMeta=columnMeta;sync();state.project=project;populateProjects();render()}
function sync(){state.projects=state.tables.PROJETS||[];state.meetings=state.tables.REUNIONS||[];state.people=state.tables.INTERLOCUTEURS||[]}
function normalizeTableNames(v){const rows=Array.isArray(v)?v:Array.isArray(v?.tables)?v.tables:[];return rows.map(r=>typeof r==="string"?r:r?.id??r?.tableId??r?.name??"").filter(Boolean)}
function columnar(c){if(!c||typeof c!=="object")return[];const names=Object.keys(c).filter(n=>Array.isArray(c[n])),length=Math.max(0,...names.map(n=>c[n].length));return Array.from({length},(_,i)=>Object.fromEntries(names.map(n=>[n,c[n][i]])))}
async function fetchSchema(names){const[t,c]=await Promise.all([window.grist.docApi.fetchTable("_grist_Tables"),window.grist.docApi.fetchTable("_grist_Tables_column")]),ids=new Map(columnar(t).map(r=>[String(r.id),r.tableId])),rows=columnar(c);state.writable=Object.fromEntries(names.map(table=>[table,new Set(rows.filter(col=>ids.get(String(col.parentId))===table&&isWritableColumn(col)).map(col=>col.colId))]));state.columnMeta=Object.fromEntries(names.map(table=>[table,Object.fromEntries(rows.filter(col=>ids.get(String(col.parentId))===table).map(col=>[col.colId,{type:col.type,formula:col.formula,isFormula:col.isFormula,parentId:col.parentId,tableTarget:referenceTarget(col.type),choices:metadataChoices(col.widgetOptions)}]))]))}
function isWritableColumn(column){return !(isTrue(column?.isFormula)&&hasValue(column?.formula))}
function referenceTarget(type){const match=/^Ref(?:List)?:([^:]+)/i.exec(displayValue(type));return match?.[1]||""}
function metadataChoices(raw){try{const value=typeof raw==="string"?JSON.parse(raw):raw,choices=value?.choices;return Array.isArray(choices)?choices.map(displayValue).filter(hasValue):[]}catch{return[]}}
function isDemo(){return["localhost","127.0.0.1"].includes(location.hostname)&&self===top&&new URLSearchParams(location.search).get("demo")==="1"&&window.MEETINGS_DEMO_DATA}

function projectMeetings(){return state.project?state.meetings.filter(m=>referenceIds(m.Projet).some(id=>same(id,state.project.id))).sort((a,b)=>dateValue(b.Date_reunion??b.Date)-dateValue(a.Date_reunion??a.Date)):[]}
function filtered(rows){const today=startToday(),q=normalizeText(state.search);return rows.filter(m=>{const d=dateValue(m.Date_reunion??m.Date),ok=state.filter==="all"||(state.filter==="upcoming"&&d>=today)||(state.filter==="past"&&d>0&&d<today);return ok&&normalizeText([m.Objet,agendaValue(m),m.Compte_rendu,m.Lieu,peopleValue(m.Participants)].filter(hasValue).join(" ")).includes(q)})}
function populateProjects(){ui.projectSelector.replaceChildren(...[...state.projects].sort((a,b)=>textOr(a.Nom_projet,"").localeCompare(textOr(b.Nom_projet,""),"fr")).map(p=>option(p.id,textOr(p.Nom_projet,`Projet ${p.id}`))));ui.projectSelector.disabled=!state.projects.length||Boolean(window.PilotageContext?.isProjectMode)}
function firstProject(){return state.projects.find(p=>same(p.id,window.PilotageContext?.projectId))||state.projects.find(p=>!isTrue(p.Archive)&&!["termine","abandonne"].includes(normalizeText(p.Statut)))||state.projects[0]||null}
function render(){if(!state.project){showState("Aucun projet sélectionné","Sélectionnez une ligne dans PROJETS.");return}const rows=projectMeetings(),today=startToday(),participants=new Set(rows.flatMap(row=>referenceIds(row.Participants)));ui.projectSelector.value=String(state.project.id);ui.projectName.textContent=textOr(state.project.Nom_projet,"Projet sans nom");ui.total.textContent=`${rows.length} ${rows.length>1?"réunions":"réunion"}`;const kpis=[["Total",rows.length],["À venir",rows.filter(r=>dateValue(r.Date_reunion??r.Date)>=today).length],["Passées",rows.filter(r=>{const d=dateValue(r.Date_reunion??r.Date);return d>0&&d<today}).length],["Participants",participants.size]];ui.kpis.replaceChildren(...kpis.map(([l,v])=>{const c=element("article","card meeting-kpi");c.append(textElement("span",l,"meeting-kpi__label"),textElement("strong",v,"meeting-kpi__value"));return c}));renderList(filtered(rows));ui.state.hidden=true;ui.content.hidden=false}
function renderList(rows){ui.results.textContent=`${rows.length} résultat${rows.length>1?"s":""}`;ui.list.replaceChildren(...(rows.length?rows.map(meetingCard):[textElement("p","Aucune réunion ne correspond à ces critères.","card empty-results")]))}
function meetingCard(m){const card=ui.template.content.firstElementChild.cloneNode(true);card.dataset.meetingId=String(m.id);card.querySelector(".meeting-card__date").textContent=formatDate(m.Date_reunion??m.Date)||"Date non renseignée";card.querySelector(".meeting-card__title").textContent=textOr(m.Objet,"Réunion sans objet");const upcoming=isUpcoming(m),badges=card.querySelector(".meeting-card__badges");badges.append(badge(upcoming?"À venir":"Passée",upcoming?"warning":"success"));const dl=card.querySelector(".meeting-card__details");definition(dl,"Heure",m.Heure);definition(dl,"Participants",peopleValue(m.Participants));definition(dl,"Lieu",m.Lieu);const sections=card.querySelector(".meeting-card__sections");note(sections,"Ordre du jour",agendaValue(m),"info",true);note(sections,"Compte rendu",m.Compte_rendu,"info");card.querySelector("[data-edit]").addEventListener("click",()=>openMeetingForm(m));const version=card.querySelector("[data-version]");if(hasValue(m.Compte_rendu)&&!upcoming){const availability=versionAvailability();version.hidden=false;version.disabled=!availability.ok;version.title=availability.reason;version.addEventListener("click",()=>openVersionForm(m))}if(!dl.children.length)dl.remove();if(!sections.children.length)sections.remove();return card}
function compatibleReference(table,name,target){const type=displayValue(state.columnMeta?.[table]?.[name]?.type),match=/^Ref(?:List)?:([^:]+)/i.exec(type);return Boolean(match)&&normalizeText(match[1])===normalizeText(target)}
function definition(c,l,v){if(!hasValue(v))return;const d=element("div");d.append(textElement("dt",l),textElement("dd",v));c.append(d)}
function note(c,l,v,kind,open=false){if(!hasValue(v))return;const d=element("details",`meeting-note meeting-note--${kind}`);d.open=open;d.append(textElement("summary",l),textElement("p",v));c.append(d)}

function bindControls(){ui.projectSelector.addEventListener("change",()=>{state.project=state.projects.find(p=>same(p.id,ui.projectSelector.value))||null;render()});ui.filters.addEventListener("click",e=>{const b=e.target.closest("[data-filter]");if(!b)return;state.filter=b.dataset.filter;ui.filters.querySelectorAll("[data-filter]").forEach(x=>x.setAttribute("aria-pressed",String(x===b)));render()});ui.search.addEventListener("input",()=>{state.search=ui.search.value;render()});ui.newMeeting.addEventListener("click",()=>openMeetingForm());document.querySelectorAll("dialog [data-close]").forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));ui.meetingForm.addEventListener("submit",saveMeeting);ui.versionForm.addEventListener("submit",saveVersion)}
const hasColumn=(table,name)=>Boolean(state.writable?.[table]?.has(name));
const agendaColumn=()=>AGENDA_COLUMNS.find(name=>hasColumn("REUNIONS",name))||"",agendaValue=meeting=>{if(!meeting)return"";const name=AGENDA_COLUMNS.find(column=>hasValue(meeting[column]));return name?meeting[name]:""};
function openMeetingForm(meeting=null){state.editing=meeting;const author=state.currentUser?.personId,agenda=agendaColumn();state.participantIds=validPersonIds(meeting?.Participants??(author?[author]:[]));state.showAllPeople=false;state.participantSearch="";ui.meetingForm.reset();$("#meeting-form-title").textContent=meeting?"Modifier la réunion":"Nouvelle réunion";ui.meetingSubmit.textContent=meeting?"Enregistrer les modifications":"Créer la réunion";const general=[["Projet","Projet","project",meeting?.Projet??state.project?.id,true],["Objet","Titre de la réunion","text",meeting?.Objet??"",true],["Date_reunion","Date",baseColumnType("REUNIONS","Date_reunion")==="DateTime"?"datetime-local":"date",meeting?.Date_reunion??"",false],["Heure","Horaire","time",meeting?.Heure??"",false],["Lieu","Lieu", "text",meeting?.Lieu??"",false]];ui.meetingGeneral.replaceChildren(...general.filter(([name])=>hasColumn("REUNIONS",name)||["Projet","Date_reunion","Objet"].includes(name)).map(args=>buildField(...args)));ui.meetingAgenda.replaceChildren(...(agenda?[buildField(agenda,"Ordre du jour (facultatif)","textarea",agendaValue(meeting))]:[]));ui.meetingParticipants.replaceChildren(...(hasColumn("REUNIONS","Participants")?[participantField("Participants")]:[]));ui.meetingReport.replaceChildren(...(hasColumn("REUNIONS","Compte_rendu")?[buildField("Compte_rendu","Compte rendu","textarea",meeting?.Compte_rendu??"")]:[]));const message=ui.meetingDialog.querySelector(".form-message"),report=ui.meetingForm.elements.Compte_rendu;if(meeting&&hasValue(meeting.Compte_rendu)&&report){report.disabled=true;report.closest(".form-field")?.classList.add("form-field--locked");message.textContent="Le compte rendu existant est verrouillé. Sa modification passe par une nouvelle version avec motif et approbation."}else message.textContent=agenda?"":"La colonne d’ordre du jour est absente de REUNIONS. Ajoutez Ordre_du_jour (ou conservez Points_cles) pour activer ce champ.";ui.meetingDialog.showModal()}
function buildField(name,label,type,value,required=false,choices=[]){if(type==="participants")return participantField(label);const wrap=element("label",`form-field${type==="textarea"?" form-field--wide":""}${required?" form-field--required":""}`);wrap.append(textElement("span",label,"form-field__label"));let c;if(type==="textarea"){c=element("textarea");c.rows=4}else if(["project","person","choice"].includes(type)){c=element("select");if(type==="choice")c.append(...choices.map(v=>option(v,v)));else{const rows=type==="project"?state.projects:state.people;c.append(option("",required?"Choisir":"Non renseigné"),...rows.map(r=>option(r.id,type==="project"?textOr(r.Nom_projet,`Projet ${r.id}`):personLabel(r))))}}else{c=element("input");c.type=type}c.className="form-field__control";c.name=name;c.required=required;if(type==="checkbox")c.checked=isTrue(value);else if(type==="date")c.value=inputDate(value);else if(type==="datetime-local")c.value=inputDateTime(value);else c.value=displayValue(value);wrap.append(c);return wrap}
function participantField(label){const wrap=element("fieldset","form-field form-field--wide participant-picker");wrap.append(textElement("legend",label,"form-field__label"));const chips=element("div","participant-chips");chips.dataset.chips="";chips.setAttribute("aria-live","polite");const search=element("input","form-field__control participant-search");search.type="search";search.placeholder="Rechercher par nom, organisme ou fonction…";search.setAttribute("aria-label","Rechercher un participant");search.addEventListener("input",()=>{state.participantSearch=search.value;renderPicker(wrap)});const heading=textElement("p","Interlocuteurs du projet","participant-picker__heading"),options=element("div","participant-options");options.dataset.options="";const toggle=element("button","button button--link participant-toggle");toggle.type="button";toggle.addEventListener("click",()=>{state.showAllPeople=!state.showAllPeople;renderPicker(wrap)});wrap.append(chips,search,heading,options,toggle);renderPicker(wrap);return wrap}
function renderPicker(wrap){const chips=wrap.querySelector("[data-chips]");chips.replaceChildren(...state.participantIds.map(id=>{const p=person(id),chip=element("span","participant-chip"),remove=element("button");chip.append(textElement("span",p?personLabel(p):`Interlocuteur ${id}`));remove.type="button";remove.textContent="×";remove.setAttribute("aria-label",`Retirer ${p?personLabel(p):id}`);remove.addEventListener("click",()=>{state.participantIds=state.participantIds.filter(x=>!same(x,id));renderPicker(wrap)});chip.append(remove);return chip}));const q=normalizeText(state.participantSearch),pool=state.showAllPeople?state.people:projectPeople(),available=pool.filter(p=>!state.participantIds.some(id=>same(id,p.id))).filter(p=>!q||personSearch(p).includes(q)),options=wrap.querySelector("[data-options]");options.replaceChildren(...(available.length?available.map(p=>{const b=element("button","participant-option");b.type="button";b.append(textElement("strong",personLabel(p),"participant-option__name"));if(hasValue(p.Fonction))b.append(textElement("span",p.Fonction,"participant-option__function"));if(hasValue(p.Organisme))b.append(textElement("span",p.Organisme,"participant-option__organisation"));b.addEventListener("click",()=>{if(!state.participantIds.some(id=>same(id,p.id)))state.participantIds.push(String(p.id));renderPicker(wrap)});return b}):[textElement("p",q?"Aucun interlocuteur ne correspond à la recherche.":"Tous les interlocuteurs proposés sont sélectionnés.","participant-empty")]));wrap.querySelector(".participant-picker__heading").textContent=state.showAllPeople?"Annuaire des interlocuteurs":"Interlocuteurs du projet";const t=wrap.querySelector(".participant-toggle");t.textContent=state.showAllPeople?"Afficher seulement les interlocuteurs du projet":"Afficher tous les interlocuteurs";t.setAttribute("aria-expanded",String(state.showAllPeople))}
function projectPeople(){const values=PROJECT_PEOPLE.map(n=>state.project?.[n]);for(const table of ["ACTIONS","CONSIGNES_POLITIQUES","REUNIONS"]){for(const row of state.tables[table]||[]){if(referenceIds(row.Projet).some(id=>same(id,state.project?.id)))values.push(row.Responsable,row.Demandee_par,row.Emetteur,row.Destinataires,row.Participants,row.Saisi_par)}}return [...new Map(validPersonIds(values).map(person).filter(Boolean).map(p=>[String(p.id),p])).values()]}
function validPersonIds(v){const known=new Set(state.people.map(p=>String(p.id)));return[...new Set(referenceIds(v).filter(id=>id!=="0"&&known.has(id)))]}
const person=id=>state.people.find(p=>same(p.id,id)),personLabel=p=>textOr(p.Nom_complet,[p.Prenom,p.Nom].filter(hasValue).join(" ")||`Interlocuteur ${p.id}`),personSearch=p=>normalizeText([p.Nom_complet,p.Prenom,p.Nom,p.Organisme,p.Fonction].filter(hasValue).join(" "));
function formValues(form,table){const values={};for(const c of form.elements){const n=c.name;if(c.disabled||!n||(!hasColumn(table,n)&&!(table==="REUNIONS"&&["Projet","Date_reunion","Objet"].includes(n))))continue;if(c.type==="checkbox")values[n]=c.checked;else if(!hasValue(c.value))continue;else if(["Projet","Saisi_par","Responsable","Attribuee_a"].includes(n))values[n]=Number(c.value);else if(c.type==="date")values[n]=new Date(`${c.value}T00:00:00`).getTime()/1000;else if(c.type==="datetime-local")values[n]=new Date(c.value).getTime()/1000;else if(state.columnMeta?.[table]?.[n]?.type==="ChoiceList")values[n]=["L",c.value.trim()];else values[n]=c.value.trim()}if(table==="REUNIONS"&&hasColumn(table,"Participants"))values.Participants=["L",...state.participantIds.map(Number).filter(n=>Number.isFinite(n)&&n>0)];return values}
async function saveMeeting(e){e.preventDefault();const fields=formValues(ui.meetingForm,"REUNIONS");if(!hasValue(fields.Projet)||!hasValue(fields.Objet)){ui.meetingDialog.querySelector(".form-message").textContent="Le projet et l’objet sont obligatoires.";return}try{if(!state.editing&&hasColumn("REUNIONS","Saisi_par"))fields.Saisi_par=window.PilotageCurrentUser.requirePersonId(state.currentUser);const result=await write([[state.editing?"UpdateRecord":"AddRecord","REUNIONS",state.editing?.id??null,fields]]),meeting=state.editing?state.meetings.find(r=>same(r.id,state.editing.id)):result.added.REUNIONS?.[0];if(!meeting)throw Error("La ligne a été écrite mais n’a pas été retrouvée après relecture de REUNIONS.");if(!referenceIds(meeting.Projet).some(id=>same(id,fields.Projet)))throw Error(`La réunion ${meeting.id} existe, mais sa référence Projet est incorrecte.`);ui.meetingDialog.close();render();focusMeeting(meeting.id);feedback(state.editing?"Réunion modifiée.":"Réunion créée et affichée dans le projet.")}catch(error){ui.meetingDialog.querySelector(".form-message").textContent=`Écriture impossible — ${exactError(error)}`}}
function versionAvailability(){if(!state.tableNames.includes("REUNIONS_VERSIONS")&&!Object.hasOwn(state.tables,"REUNIONS_VERSIONS"))return{ok:false,reason:"La table REUNIONS_VERSIONS doit d’abord être créée dans Grist."};const required=["Reunion","Numero_version","Compte_rendu","Motif_modification","Demandeur","Approbateur"],missing=required.filter(name=>!hasColumn("REUNIONS_VERSIONS",name));if(missing.length)return{ok:false,reason:`Colonnes modifiables manquantes dans REUNIONS_VERSIONS : ${missing.join(", ")}.`};if(!compatibleReference("REUNIONS_VERSIONS","Reunion","REUNIONS"))return{ok:false,reason:"REUNIONS_VERSIONS.Reunion doit être une référence vers REUNIONS."};return{ok:true,reason:""}}
function meetingVersions(meeting){return(state.tables.REUNIONS_VERSIONS||[]).filter(row=>referenceIds(row.Reunion).some(id=>same(id,meeting.id)))}
function openVersionForm(meeting){const availability=versionAvailability();if(!availability.ok){feedback(availability.reason);return}state.versionMeeting=meeting;ui.versionForm.reset();ui.versionContext.textContent=`Réunion : ${textOr(meeting.Objet,`n° ${meeting.id}`)}. La modification sera enregistrée comme une nouvelle version approuvée.`;const defs=[["Compte_rendu","Compte rendu corrigé","textarea",meeting.Compte_rendu],["Motif_modification","Motif de la modification","textarea",""],["Approbateur","Modification approuvée par","person",""]];ui.versionFields.replaceChildren(...defs.filter(([name])=>hasColumn("REUNIONS_VERSIONS",name)).map(([name,label,type,value])=>buildField(name,label,type,value)));ui.versionDialog.querySelector(".form-message").textContent="L’approbateur doit être différent de la personne qui demande la modification.";ui.versionDialog.showModal()}
function versionFields(meeting,form){const author=window.PilotageCurrentUser.requirePersonId(state.currentUser),values={},now=Math.floor(Date.now()/1000),formData=new FormData(form);for(const name of ["Compte_rendu","Motif_modification"]){const value=displayValue(formData.get(name));if(value&&hasColumn("REUNIONS_VERSIONS",name))values[name]=value}const approver=Number(formData.get("Approbateur"));if(approver&&hasColumn("REUNIONS_VERSIONS","Approbateur"))values.Approbateur=approver;if(hasColumn("REUNIONS_VERSIONS","Demandeur"))values.Demandeur=author;values.Reunion=Number(meeting.id);values.Numero_version=Math.max(0,...meetingVersions(meeting).map(row=>Number(row.Numero_version)||0))+1;if(hasColumn("REUNIONS_VERSIONS","Auteur"))values.Auteur=author;if(hasColumn("REUNIONS_VERSIONS","Date_version"))values.Date_version=now;if(hasColumn("REUNIONS_VERSIONS","Statut_demande"))values.Statut_demande="Approuvée";return values}
async function saveVersion(e){e.preventDefault();const meeting=state.versionMeeting,message=ui.versionDialog.querySelector(".form-message");try{if(!meeting)throw Error("La réunion concernée est introuvable.");const fields=versionFields(meeting,ui.versionForm);if(!hasValue(fields.Compte_rendu)||!hasValue(fields.Motif_modification)||!fields.Demandeur||!fields.Approbateur)throw Error("Le compte rendu, le motif, le demandeur et l’approbateur sont obligatoires.");if(same(fields.Demandeur,fields.Approbateur))throw Error("Le demandeur et l’approbateur doivent être deux personnes différentes.");const versions=meetingVersions(meeting),actions=[];if(!versions.length){const initial={Reunion:Number(meeting.id),Numero_version:1,Compte_rendu:meeting.Compte_rendu};if(hasColumn("REUNIONS_VERSIONS","Auteur")&&hasValue(meeting.Saisi_par))initial.Auteur=Number(referenceIds(meeting.Saisi_par)[0]);if(hasColumn("REUNIONS_VERSIONS","Date_version"))initial.Date_version=Math.floor((dateValue(meeting.Date_reunion)||Date.now())/1000);if(hasColumn("REUNIONS_VERSIONS","Motif_modification"))initial.Motif_modification="Version initiale conservée avant la première modification.";actions.push(["AddRecord","REUNIONS_VERSIONS",null,initial]);fields.Numero_version=2}actions.push(["AddRecord","REUNIONS_VERSIONS",null,fields]);actions.push(["UpdateRecord","REUNIONS",meeting.id,{Compte_rendu:fields.Compte_rendu}]);await write(actions);ui.versionDialog.close();render();focusMeeting(meeting.id);feedback(`Version ${fields.Numero_version} approuvée et enregistrée. L’ancienne version est conservée.`)}catch(error){message.textContent=`Enregistrement impossible — ${exactError(error)}`}}
async function write(actions){if(state.busy)throw Error("Une écriture est déjà en cours.");state.busy=true;const before=Object.fromEntries(actions.map(([,t])=>[t,new Set((state.tables[t]||[]).map(r=>String(r.id))) ]));try{if(state.demo){for(const[type,table,id,fields]of actions){if(type==="AddRecord"){const next=Math.max(0,...(state.tables[table]||[]).map(r=>Number(r.id)||0))+1;state.tables[table].push({id:next,...fields})}else{const row=state.tables[table].find(r=>same(r.id,id));if(!row)throw Error(`Ligne ${id} introuvable dans ${table}.`);Object.assign(row,fields)}}}else{await timeout(window.PilotageTestMode.applyUserActions(actions),"écriture dans Grist");state.tables=await fetchTables(availableTables());sync()}const added={};for(const[,table]of actions)added[table]=(state.tables[table]||[]).filter(r=>!before[table]?.has(String(r.id)));return{added}}finally{state.busy=false}}

function focusMeeting(id){requestAnimationFrame(()=>{const c=ui.list.querySelector(`[data-meeting-id="${CSS.escape(String(id))}"]`);if(c){c.classList.add("meeting-card--highlight");c.scrollIntoView({block:"nearest",behavior:"smooth"});setTimeout(()=>c.classList.remove("meeting-card--highlight"),1800)}})}
function feedback(m){ui.feedback.textContent=m;ui.feedback.hidden=false;setTimeout(()=>ui.feedback.hidden=true,4000)}function showState(t,m){ui.content.hidden=true;const b=element("div");b.append(textElement("strong",t),textElement("p",m));ui.state.replaceChildren(b);ui.state.hidden=false}
const peopleValue=v=>referenceIds(v).map(id=>person(id)?personLabel(person(id)):id).join(", "),referenceIds=v=>!hasValue(v)?[]:(Array.isArray(v)?v.flat(3):[v]).filter(x=>x!=="L"&&hasValue(x)).map(String),same=(a,b)=>String(a)===String(b),startToday=()=>{const d=new Date;d.setHours(0,0,0,0);return d.getTime()},isUpcoming=m=>dateValue(m.Date_reunion??m.Date)>=startToday(),baseColumnType=(table,name)=>displayValue(state.columnMeta?.[table]?.[name]?.type).split(":")[0];
function dateValue(v){if(!hasValue(v))return 0;const d=new Date(typeof v==="number"?v*1000:v);return Number.isNaN(d.getTime())?0:d.getTime()}function formatDate(v){const t=dateValue(v);return t?new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric",timeZone:"Europe/Paris"}).format(new Date(t)):""}const inputDate=v=>dateValue(v)?new Date(dateValue(v)).toISOString().slice(0,10):"",inputDateTime=v=>{const t=dateValue(v);if(!t)return"";const d=new Date(t),local=new Date(t-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)},hasValue=v=>v!==null&&v!==undefined&&String(v).trim()!=="",displayValue=v=>Array.isArray(v)?v.filter(x=>x!=="L").map(displayValue).join(", "):hasValue(v)?String(v).trim():"",textOr=(v,f)=>hasValue(v)?displayValue(v):f,normalizeText=v=>displayValue(v).toLocaleLowerCase("fr-FR").normalize("NFD").replace(/[\u0300-\u036f]/g,""),isTrue=v=>v===true||v===1||["true","vrai","oui","1"].includes(normalizeText(v)),exactError=e=>e instanceof Error?`${e.name} : ${e.message}`:String(e);
function statusKind(v){const t=normalizeText(v);return/(fait|realise|termine|valide)/.test(t)?"success":/(retard|bloque|annule)/.test(t)?"danger":/(arbitr|decid)/.test(t)?"arbitration":"info"}function badge(v,k){return textElement("span",v,`badge badge--${k}`)}function option(v,l){const o=element("option");o.value=v;o.textContent=l;return o}function element(tag,cls){const n=document.createElement(tag);if(cls)n.className=cls;return n}function textElement(tag,v,cls){const n=element(tag,cls);n.textContent=displayValue(v);return n}
const renderMeetingsView = render;
render = function renderWithProjectReturn() {
  renderMeetingsView();
  window.PilotageContext?.configureProjectReturn(document.querySelector("#project-return"), state.project);
};

initialize();
