"use strict";
const REQUIRED_TABLES=["PROJETS","REUNIONS","INTERLOCUTEURS"],OPTIONAL_TABLES=["ACTIONS","CONSIGNES_POLITIQUES","ARBITRAGES_DECISIONS"],REUNION_COLUMNS=["Reunion_origine","Reunion","Origine_reunion"];
const FOLLOWUPS={ACTIONS:{label:"Action",button:"+ Action",texts:["Action","Intitule","Sujet"],initial:["Points_cles","Objet"]},CONSIGNES_POLITIQUES:{label:"Consigne",button:"+ Consigne",texts:["Consigne","Texte","Sujet"],initial:["Decisions_prises","Points_cles","Objet"]},ARBITRAGES_DECISIONS:{label:"Décision",button:"+ Décision",texts:["Sujet","Decision","Decision_prise"],initial:["Arbitrage_attendu","Decisions_prises","Objet"]}};
const MEETING_FIELDS=[["Projet","Projet","project"],["Date_reunion","Date","date"],["Heure","Heure","time"],["Objet","Objet","text"],["Type_reunion","Type de réunion","text"],["Lieu","Lieu","text"],["Participants","Participants","participants"],["Compte_rendu","Compte rendu","textarea"],["Points_cles","Points clés","textarea"],["Decisions_prises","Décisions prises","textarea"],["Arbitrage_attendu","Décision à prendre","textarea"],["Prochaine_reunion","Prochaine réunion","date"],["Saisi_par","Saisi par","person"],["CR_finalise","Compte rendu finalisé","checkbox"]];
const PROJECT_PEOPLE=["Responsable","Agent_pilote","Elu_pilote","Interlocuteurs","Membres","Membres_projet","Equipe_projet","Partenaires"];
const state={project:null,projects:[],meetings:[],people:[],tables:{},writable:null,columnMeta:{},tableNames:[],filter:"all",search:"",demo:false,editing:null,participantIds:[],showAllPeople:false,participantSearch:"",followupMeeting:null,busy:false};
const $=s=>document.querySelector(s),ui={state:$("#interface-state"),content:$("#meetings-content"),projectName:$("#project-name"),projectSelector:$("#project-selector"),total:$("#meeting-count"),kpis:$("#meeting-kpis"),filters:$("#filter-list"),search:$("#meeting-search"),results:$("#results-count"),list:$("#meeting-list"),template:$("#meeting-template"),newMeeting:$("#new-meeting"),meetingDialog:$("#meeting-dialog"),meetingForm:$("#meeting-form"),meetingFields:$("#meeting-fields"),followupDialog:$("#followup-dialog"),followupForm:$("#followup-form"),followupFields:$("#followup-fields"),feedback:$("#feedback")};

async function initialize(){bindControls();try{if(isDemo()){state.demo=true;state.tableNames=[...REQUIRED_TABLES,...OPTIONAL_TABLES];applyData(window.MEETINGS_DEMO_DATA.project,window.MEETINGS_DEMO_DATA.tables,window.MEETINGS_DEMO_DATA.columnMeta);return}if(!window.grist?.docApi)throw Error("L’API Grist n’est pas disponible.");await timeout(Promise.resolve(window.grist.ready({requiredAccess:"full"})),"initialisation de Grist");state.tableNames=normalizeTableNames(await timeout(window.grist.docApi.listTables(),"détection des tables"));const missing=REQUIRED_TABLES.filter(n=>!state.tableNames.includes(n));if(missing.length)throw Error(`Tables Grist introuvables : ${missing.join(", ")}.`);const names=availableTables();state.tables=await fetchTables(names);await fetchSchema(names);sync();populateProjects();state.project=firstProject();window.grist.onRecord(record=>{const p=record&&state.projects.find(row=>same(row.id,record.id));if(p){state.project=p;render()}});render()}catch(error){console.error(error);showState("Connexion à Grist impossible",exactError(error))}}
const availableTables=()=>[...REQUIRED_TABLES,...OPTIONAL_TABLES.filter(n=>state.tableNames.includes(n))];
async function fetchTables(names){return Object.fromEntries(await Promise.all(names.map(async n=>[n,columnar(await timeout(window.grist.docApi.fetchTable(n),`lecture de ${n}`))])))}
function timeout(p,label,delay=10000){return Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(Error(`Délai dépassé pendant : ${label}.`)),delay))])}
function applyData(project,tables,columnMeta={}){state.tables=tables;state.writable=Object.fromEntries(Object.entries(tables).map(([n,rows])=>[n,new Set(rows.flatMap(Object.keys))]));state.columnMeta=columnMeta;sync();state.project=project;populateProjects();render()}
function sync(){state.projects=state.tables.PROJETS||[];state.meetings=state.tables.REUNIONS||[];state.people=state.tables.INTERLOCUTEURS||[]}
function normalizeTableNames(v){const rows=Array.isArray(v)?v:Array.isArray(v?.tables)?v.tables:[];return rows.map(r=>typeof r==="string"?r:r?.id??r?.tableId??r?.name??"").filter(Boolean)}
function columnar(c){if(!c||typeof c!=="object")return[];const names=Object.keys(c).filter(n=>Array.isArray(c[n])),length=Math.max(0,...names.map(n=>c[n].length));return Array.from({length},(_,i)=>Object.fromEntries(names.map(n=>[n,c[n][i]])))}
async function fetchSchema(names){const[t,c]=await Promise.all([window.grist.docApi.fetchTable("_grist_Tables"),window.grist.docApi.fetchTable("_grist_Tables_column")]),ids=new Map(columnar(t).map(r=>[String(r.id),r.tableId])),rows=columnar(c);state.writable=Object.fromEntries(names.map(table=>[table,new Set(rows.filter(col=>ids.get(String(col.parentId))===table&&isWritableColumn(col)).map(col=>col.colId))]));state.columnMeta=Object.fromEntries(names.map(table=>[table,Object.fromEntries(rows.filter(col=>ids.get(String(col.parentId))===table).map(col=>[col.colId,{type:col.type,formula:col.formula,isFormula:col.isFormula,parentId:col.parentId,tableTarget:referenceTarget(col.type),choices:metadataChoices(col.widgetOptions)}]))]))}
function isWritableColumn(column){return !(isTrue(column?.isFormula)&&hasValue(column?.formula))}
function referenceTarget(type){const match=/^Ref(?:List)?:([^:]+)/i.exec(displayValue(type));return match?.[1]||""}
function metadataChoices(raw){try{const value=typeof raw==="string"?JSON.parse(raw):raw,choices=value?.choices;return Array.isArray(choices)?choices.map(displayValue).filter(hasValue):[]}catch{return[]}}
function isDemo(){return["localhost","127.0.0.1"].includes(location.hostname)&&self===top&&new URLSearchParams(location.search).get("demo")==="1"&&window.MEETINGS_DEMO_DATA}

function projectMeetings(){return state.project?state.meetings.filter(m=>referenceIds(m.Projet).some(id=>same(id,state.project.id))).sort((a,b)=>dateValue(b.Date_reunion??b.Date)-dateValue(a.Date_reunion??a.Date)):[]}
function filtered(rows){const today=startToday(),q=normalizeText(state.search);return rows.filter(m=>{const d=dateValue(m.Date_reunion??m.Date),ok=state.filter==="all"||(state.filter==="upcoming"&&d>=today)||(state.filter==="past"&&d>0&&d<today)||(state.filter==="decisions"&&(hasValue(m.Decisions_prises)||hasValue(m.Arbitrage_attendu)));return ok&&normalizeText([m.Objet,m.Type_reunion,m.Points_cles,m.Decisions_prises].filter(hasValue).join(" ")).includes(q)})}
function populateProjects(){ui.projectSelector.replaceChildren(...[...state.projects].sort((a,b)=>textOr(a.Nom_projet,"").localeCompare(textOr(b.Nom_projet,""),"fr")).map(p=>option(p.id,textOr(p.Nom_projet,`Projet ${p.id}`))));ui.projectSelector.disabled=!state.projects.length||Boolean(window.PilotageContext?.isProjectMode)}
function firstProject(){return state.projects.find(p=>same(p.id,window.PilotageContext?.projectId))||state.projects.find(p=>!isTrue(p.Archive)&&!["termine","abandonne"].includes(normalizeText(p.Statut)))||state.projects[0]||null}
function render(){if(!state.project){showState("Aucun projet sélectionné","Sélectionnez une ligne dans PROJETS.");return}const rows=projectMeetings(),today=startToday();ui.projectSelector.value=String(state.project.id);ui.projectName.textContent=textOr(state.project.Nom_projet,"Projet sans nom");ui.total.textContent=`${rows.length} ${rows.length>1?"réunions":"réunion"}`;const kpis=[["Total",rows.length],["À venir",rows.filter(r=>dateValue(r.Date_reunion??r.Date)>=today).length],["Décisions prises",rows.filter(r=>hasValue(r.Decisions_prises)).length],["Décisions à prendre",rows.filter(r=>hasValue(r.Arbitrage_attendu)).length]];ui.kpis.replaceChildren(...kpis.map(([l,v])=>{const c=element("article","card meeting-kpi");c.append(textElement("span",l,"meeting-kpi__label"),textElement("strong",v,"meeting-kpi__value"));return c}));renderList(filtered(rows));ui.state.hidden=true;ui.content.hidden=false}
function renderList(rows){ui.results.textContent=`${rows.length} résultat${rows.length>1?"s":""}`;ui.list.replaceChildren(...(rows.length?rows.map(meetingCard):[textElement("p","Aucune réunion ne correspond à ces critères.","card empty-results")]))}
function meetingCard(m){const card=ui.template.content.firstElementChild.cloneNode(true);card.dataset.meetingId=String(m.id);card.querySelector(".meeting-card__date").textContent=formatDate(m.Date_reunion??m.Date)||"Date non renseignée";card.querySelector(".meeting-card__title").textContent=textOr(m.Objet,"Réunion sans objet");const badges=card.querySelector(".meeting-card__badges");if(hasValue(m.Type_reunion))badges.append(badge(m.Type_reunion,"info"));badges.append(badge(isUpcoming(m)?"À venir":"Passée",isUpcoming(m)?"warning":"success"));const dl=card.querySelector(".meeting-card__details");definition(dl,"Heure",m.Heure);definition(dl,"Participants",peopleValue(m.Participants));definition(dl,"Lieu",m.Lieu);definition(dl,"Durée",m.Duree);definition(dl,"Organisateur",peopleValue(m.Organisateur??m.Responsable));const sections=card.querySelector(".meeting-card__sections");note(sections,"Pourquoi / compte rendu",m.Compte_rendu,"info");note(sections,"Points clés",m.Points_cles,"info",true);note(sections,"Décisions prises",m.Decisions_prises,"decision",true);note(sections,"Décision à prendre",m.Arbitrage_attendu,"arbitration",true);note(sections,"Prochaines étapes",m.Prochaines_etapes??m.Prochaine_etape,"info");card.insertBefore(followupSection(m),card.querySelector(".meeting-card__actions"));card.querySelector("[data-edit]").addEventListener("click",()=>openMeetingForm(m));if(!dl.children.length)dl.remove();if(!sections.children.length)sections.remove();return card}
function followupSection(meeting){const section=element("section","meeting-followups"),head=element("div","meeting-followups__header"),rows=followupsFor(meeting);head.append(textElement("h4","Suites données à cette réunion"),badge(`${rows.length} suite${rows.length>1?"s":""}`,"info"));section.append(head);if(rows.length){const list=element("ul","meeting-followups__list");rows.forEach(({table,row,cfg})=>{const li=element("li",`followup-item followup-item--${table.toLowerCase()}`),main=element("div");main.append(textElement("span",cfg.label,"followup-item__type"),textElement("strong",followupText(row,cfg),"followup-item__text"));li.append(main);if(hasValue(row.Statut))li.append(badge(row.Statut,statusKind(row.Statut)));list.append(li)});section.append(list)}else section.append(textElement("p","Aucune suite liée pour le moment.","meeting-followups__empty"));const actions=element("div","followup-actions");Object.entries(FOLLOWUPS).forEach(([table,cfg])=>{const availability=followupAvailability(table),command=element("div","followup-command"),b=element("button","button button--secondary");b.type="button";b.textContent=cfg.button;b.disabled=!availability.ok;if(availability.ok)b.addEventListener("click",()=>openFollowup(table,meeting));else{b.title=availability.reason;b.setAttribute("aria-describedby",`${table}-${meeting.id}-reason`);const reason=textElement("span",availability.reason,"followup-command__reason");reason.id=`${table}-${meeting.id}-reason`;command.append(b,reason);actions.append(command);return}command.append(b);actions.append(command)});section.append(actions);return section}
function followupsFor(meeting){const out=[];Object.entries(FOLLOWUPS).forEach(([table,cfg])=>{const rel=relationColumn(table,false);if(rel)(state.tables[table]||[]).filter(r=>referenceIds(r[rel]).some(id=>same(id,meeting.id))).forEach(row=>out.push({table,row,cfg}))});return out}
function relationColumn(table,writable=true){return REUNION_COLUMNS.find(n=>writable?hasColumn(table,n)&&compatibleReference(table,n,"REUNIONS"):(hasColumn(table,n)||(state.tables[table]||[]).some(r=>Object.hasOwn(r,n))))}
function compatibleReference(table,name,target){const type=displayValue(state.columnMeta?.[table]?.[name]?.type),match=/^Ref(?:List)?:([^:]+)/i.exec(type);return Boolean(match)&&normalizeText(match[1])===normalizeText(target)}
function relationDiagnostic(table){const ids=Object.keys(state.columnMeta?.[table]||{}),name=REUNION_COLUMNS.find(column=>ids.includes(column)),meta=name?state.columnMeta[table][name]:null;if(!name)return`Colonne absente. IDs reçus : ${ids.join(", ")||"aucun"}.`;if(!hasColumn(table,name))return`Colonne ${name} trouvée mais non modifiable (type brut : ${displayValue(meta.type)||"vide"}, formule : ${displayValue(meta.formula)||"vide"}, isFormula : ${displayValue(meta.isFormula)}, parentId : ${displayValue(meta.parentId)}).`;if(!compatibleReference(table,name,"REUNIONS"))return`Colonne ${name} modifiable mais référence rejetée (type brut : ${displayValue(meta.type)||"vide"}, cible interprétée : ${displayValue(meta.tableTarget)||"aucune"}, cible attendue : REUNIONS).`;return`Métadonnées système incomplètes : ${name} passe hasColumn et compatibleReference mais n’a pas été retenue.`}
function followupAvailability(table){if(!state.tableNames.includes(table)&&!Object.hasOwn(state.tables,table))return{ok:false,reason:`Table ${table} introuvable dans Grist.`};if(!hasColumn(table,"Projet")||!compatibleReference(table,"Projet","PROJETS"))return{ok:false,reason:`${table}.Projet n’est pas une référence modifiable vers PROJETS.`};const rel=relationColumn(table);if(!rel)return{ok:false,reason:relationDiagnostic(table)};return{ok:true,reason:""}}
function followupText(row,cfg){const col=cfg.texts.find(n=>hasValue(row[n]));return col?displayValue(row[col]):"Sans intitulé"}
function definition(c,l,v){if(!hasValue(v))return;const d=element("div");d.append(textElement("dt",l),textElement("dd",v));c.append(d)}
function note(c,l,v,kind,open=false){if(!hasValue(v))return;const d=element("details",`meeting-note meeting-note--${kind}`);d.open=open;d.append(textElement("summary",l),textElement("p",v));c.append(d)}

function bindControls(){ui.projectSelector.addEventListener("change",()=>{state.project=state.projects.find(p=>same(p.id,ui.projectSelector.value))||null;render()});ui.filters.addEventListener("click",e=>{const b=e.target.closest("[data-filter]");if(!b)return;state.filter=b.dataset.filter;ui.filters.querySelectorAll("[data-filter]").forEach(x=>x.setAttribute("aria-pressed",String(x===b)));render()});ui.search.addEventListener("input",()=>{state.search=ui.search.value;render()});ui.newMeeting.addEventListener("click",()=>openMeetingForm());ui.list.addEventListener("click",e=>{const button=e.target.closest(".followup-actions button");if(!button||button.disabled)return;const table=Object.entries(FOLLOWUPS).find(([,cfg])=>cfg.button===button.textContent.trim())?.[0],meetingId=button.closest("[data-meeting-id]")?.dataset.meetingId,meeting=state.meetings.find(row=>same(row.id,meetingId));if(table&&meeting&&!ui.followupDialog.open)openFollowup(table,meeting)});document.querySelectorAll("dialog [data-close]").forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));ui.meetingForm.addEventListener("submit",saveMeeting);ui.followupForm.addEventListener("submit",saveFollowup)}
const hasColumn=(table,name)=>Boolean(state.writable?.[table]?.has(name));
function openMeetingForm(meeting=null){state.editing=meeting;state.participantIds=validPersonIds(meeting?.Participants);state.showAllPeople=false;state.participantSearch="";ui.meetingForm.reset();$("#meeting-form-title").textContent=meeting?"Modifier la réunion":"Nouvelle réunion";ui.meetingFields.replaceChildren(...MEETING_FIELDS.filter(([n])=>hasColumn("REUNIONS",n)||["Projet","Date_reunion","Objet"].includes(n)).map(([n,l,t])=>buildField(n,l,t,meeting?.[n]??(n==="Projet"?state.project?.id:""))));ui.meetingDialog.querySelector(".form-message").textContent="";ui.meetingDialog.showModal()}
function buildField(name,label,type,value,choices=[]){if(type==="participants")return participantField(label);const wrap=element("label",`form-field${type==="textarea"?" form-field--wide":""}`);wrap.append(textElement("span",label,"form-field__label"));let c;if(type==="textarea"){c=element("textarea");c.rows=4}else if(["project","person","choice"].includes(type)){c=element("select");if(type==="choice")c.append(...choices.map(v=>option(v,v)));else{const rows=type==="project"?state.projects:state.people;c.append(option("","Non renseigné"),...rows.map(r=>option(r.id,type==="project"?textOr(r.Nom_projet,`Projet ${r.id}`):personLabel(r))))}}else{c=element("input");c.type=type}c.className="form-field__control";c.name=name;if(type==="checkbox")c.checked=isTrue(value);else if(type==="date")c.value=inputDate(value);else c.value=displayValue(value);wrap.append(c);return wrap}
function participantField(label){const wrap=element("fieldset","form-field form-field--wide participant-picker");wrap.append(textElement("legend",label,"form-field__label"));const chips=element("div","participant-chips");chips.dataset.chips="";chips.setAttribute("aria-live","polite");const search=element("input","form-field__control participant-search");search.type="search";search.placeholder="Rechercher par nom, organisme ou fonction…";search.setAttribute("aria-label","Rechercher un participant");search.addEventListener("input",()=>{state.participantSearch=search.value;renderPicker(wrap)});const heading=textElement("p","Interlocuteurs du projet","participant-picker__heading"),options=element("div","participant-options");options.dataset.options="";const toggle=element("button","button button--link participant-toggle");toggle.type="button";toggle.addEventListener("click",()=>{state.showAllPeople=!state.showAllPeople;renderPicker(wrap)});wrap.append(chips,search,heading,options,toggle);renderPicker(wrap);return wrap}
function renderPicker(wrap){const chips=wrap.querySelector("[data-chips]");chips.replaceChildren(...state.participantIds.map(id=>{const p=person(id),chip=element("span","participant-chip"),remove=element("button");chip.append(textElement("span",p?personLabel(p):`Interlocuteur ${id}`));remove.type="button";remove.textContent="×";remove.setAttribute("aria-label",`Retirer ${p?personLabel(p):id}`);remove.addEventListener("click",()=>{state.participantIds=state.participantIds.filter(x=>!same(x,id));renderPicker(wrap)});chip.append(remove);return chip}));const q=normalizeText(state.participantSearch),pool=state.showAllPeople?state.people:projectPeople(),available=pool.filter(p=>!state.participantIds.some(id=>same(id,p.id))).filter(p=>!q||personSearch(p).includes(q)),options=wrap.querySelector("[data-options]");options.replaceChildren(...(available.length?available.map(p=>{const b=element("button","participant-option");b.type="button";b.append(textElement("strong",personLabel(p),"participant-option__name"));if(hasValue(p.Fonction))b.append(textElement("span",p.Fonction,"participant-option__function"));if(hasValue(p.Organisme))b.append(textElement("span",p.Organisme,"participant-option__organisation"));if(hasValue(p.Type_interlocuteur))b.append(textElement("span",p.Type_interlocuteur,"participant-option__type"));b.addEventListener("click",()=>{if(!state.participantIds.some(id=>same(id,p.id)))state.participantIds.push(String(p.id));renderPicker(wrap)});return b}):[textElement("p",q?"Aucun interlocuteur ne correspond à la recherche.":"Tous les interlocuteurs proposés sont sélectionnés.","participant-empty")]));wrap.querySelector(".participant-picker__heading").textContent=state.showAllPeople?"Annuaire des interlocuteurs":"Interlocuteurs du projet";const t=wrap.querySelector(".participant-toggle");t.textContent=state.showAllPeople?"Afficher seulement les interlocuteurs du projet":"Afficher tous les interlocuteurs";t.setAttribute("aria-expanded",String(state.showAllPeople))}
function projectPeople(){const values=PROJECT_PEOPLE.map(n=>state.project?.[n]);for(const table of ["ACTIONS","CONSIGNES_POLITIQUES","REUNIONS"]){for(const row of state.tables[table]||[]){if(referenceIds(row.Projet).some(id=>same(id,state.project?.id)))values.push(row.Responsable,row.Demandee_par,row.Emetteur,row.Destinataires,row.Participants,row.Saisi_par)}}return [...new Map(validPersonIds(values).map(person).filter(Boolean).map(p=>[String(p.id),p])).values()]}
function validPersonIds(v){const known=new Set(state.people.map(p=>String(p.id)));return[...new Set(referenceIds(v).filter(id=>id!=="0"&&known.has(id)))]}
const person=id=>state.people.find(p=>same(p.id,id)),personLabel=p=>textOr(p.Nom_complet,[p.Prenom,p.Nom].filter(hasValue).join(" ")||`Interlocuteur ${p.id}`),personSearch=p=>normalizeText([p.Nom_complet,p.Prenom,p.Nom,p.Organisme,p.Fonction].filter(hasValue).join(" "));
function choiceValues(table,name){const metadata=state.columnMeta?.[table]?.[name],choices=metadata?.choices||[];if(choices.length)return[...new Set(choices)];const existing=[...new Set((state.tables[table]||[]).map(row=>displayValue(row[name])).filter(hasValue))];if(name==="Statut"&&table==="ARBITRAGES_DECISIONS")return[...new Set(["À préparer","À décider","Reportée","Décidée","Sans suite",...existing])];if(name==="Statut")return[...new Set(["À faire","En cours","À reprendre",...existing.filter(v=>!["Réalisée","Annulée"].includes(v))])];return existing.length?existing:["Non renseigné"]}
function formValues(form,table){const values={};for(const c of form.elements){const n=c.name;if(!n||n==="TargetTable"||(!hasColumn(table,n)&&!(table==="REUNIONS"&&["Projet","Date_reunion","Objet"].includes(n))))continue;if(c.type==="checkbox")values[n]=c.checked;else if(!hasValue(c.value))continue;else if(["Projet","Saisi_par","Responsable",...REUNION_COLUMNS].includes(n))values[n]=Number(c.value);else if(c.type==="date")values[n]=new Date(`${c.value}T00:00:00`).getTime()/1000;else if(state.columnMeta?.[table]?.[n]?.type==="ChoiceList")values[n]=["L",c.value.trim()];else values[n]=c.value.trim()}if(table==="REUNIONS"&&hasColumn(table,"Participants"))values.Participants=["L",...state.participantIds.map(Number).filter(n=>Number.isFinite(n)&&n>0)];return values}
async function saveMeeting(e){e.preventDefault();const fields=formValues(ui.meetingForm,"REUNIONS");if(!hasValue(fields.Projet)||!hasValue(fields.Objet)){ui.meetingDialog.querySelector(".form-message").textContent="Le projet et l’objet sont obligatoires.";return}try{const result=await write([[state.editing?"UpdateRecord":"AddRecord","REUNIONS",state.editing?.id??null,fields]]),meeting=state.editing?state.meetings.find(r=>same(r.id,state.editing.id)):result.added.REUNIONS?.[0];if(!meeting)throw Error("La ligne a été écrite mais n’a pas été retrouvée après relecture de REUNIONS.");if(!referenceIds(meeting.Projet).some(id=>same(id,fields.Projet)))throw Error(`La réunion ${meeting.id} existe, mais sa référence Projet est incorrecte.`);ui.meetingDialog.close();render();focusMeeting(meeting.id);feedback(state.editing?"Réunion modifiée.":"Réunion créée et affichée dans le projet.")}catch(error){ui.meetingDialog.querySelector(".form-message").textContent=`Écriture impossible — ${exactError(error)}`}}
function openFollowup(table,meeting){const availability=followupAvailability(table),rel=relationColumn(table);if(!availability.ok){feedback(availability.reason);return}state.followupMeeting=meeting;ui.followupForm.reset();ui.followupForm.elements.TargetTable.value=table;const cfg=FOLLOWUPS[table],text=cfg.texts.find(n=>hasColumn(table,n)),initial=cfg.initial.find(n=>hasValue(meeting[n])),statuses=choiceValues(table,"Statut"),defaultStatus=table==="ARBITRAGES_DECISIONS"?(statuses.includes("À préparer")?"À préparer":statuses[0]):(statuses.includes("À faire")?"À faire":statuses[0]);$("#followup-title").textContent=`Nouvel élément — ${cfg.label}`;const common=[["Projet","Projet","project",state.project.id],[rel,"Réunion d’origine","hidden",meeting.id],...(text?[[text,cfg.label,"textarea",initial?meeting[initial]:""]]:[])];const specific=table==="ARBITRAGES_DECISIONS"?[["Contexte","Contexte","textarea",""],["Question_a_trancher","Question à trancher","textarea",meeting.Arbitrage_attendu||""],["Options","Options","textarea",""],["Position_elue","Position élue","textarea",""],["Urgence","Urgence","choice","Normale",choiceValues(table,"Urgence")],["Echeance_decision","Échéance","date",""],["Statut","Statut","choice",defaultStatus,statuses],["Point_hebdo","Point hebdo","checkbox",true]]:[["Responsable","Responsable","person",""],["Echeance","Échéance","date",""],["Statut","Statut","choice",defaultStatus,statuses],["Commentaire","Commentaire","textarea",""]];const defs=[...common,...specific];ui.followupFields.replaceChildren(...defs.filter(([n,,t])=>t==="hidden"||hasColumn(table,n)).map(([n,l,t,v,choices])=>t==="hidden"?hidden(n,v):buildField(n,l,t,v,choices)));ui.followupDialog.querySelector(".form-message").textContent="";ui.followupDialog.showModal()}
function hidden(name,value){const i=element("input");i.type="hidden";i.name=name;i.value=value;return i}
async function saveFollowup(e){e.preventDefault();const table=ui.followupForm.elements.TargetTable.value,meetingId=state.followupMeeting?.id,rel=relationColumn(table);try{if(!meetingId||!rel)throw Error("La réunion d’origine ne peut pas être résolue.");const fields=formValues(ui.followupForm,table);if(!same(fields.Projet,state.project.id)||!same(fields[rel],meetingId))throw Error("Les références Projet ou Réunion d’origine sont absentes.");const result=await write([["AddRecord",table,null,fields]]),row=result.added[table]?.[0];if(!row)throw Error(`La ligne n’a pas été retrouvée après relecture de ${table}.`);if(!referenceIds(row[rel]).some(id=>same(id,meetingId)))throw Error(`La référence ${rel} ne pointe pas vers la réunion ${meetingId}.`);ui.followupDialog.close();render();focusMeeting(meetingId);feedback(`${FOLLOWUPS[table].label} créé et rattaché à la réunion.`)}catch(error){ui.followupDialog.querySelector(".form-message").textContent=`Création impossible — ${exactError(error)}`}}
async function write(actions){if(state.busy)throw Error("Une écriture est déjà en cours.");state.busy=true;const before=Object.fromEntries(actions.map(([,t])=>[t,new Set((state.tables[t]||[]).map(r=>String(r.id))) ]));try{if(state.demo){for(const[type,table,id,fields]of actions){if(type==="AddRecord"){const next=Math.max(0,...(state.tables[table]||[]).map(r=>Number(r.id)||0))+1;state.tables[table].push({id:next,...fields})}else{const row=state.tables[table].find(r=>same(r.id,id));if(!row)throw Error(`Ligne ${id} introuvable dans ${table}.`);Object.assign(row,fields)}}}else{await timeout(window.grist.docApi.applyUserActions(actions),"écriture dans Grist");state.tables=await fetchTables(availableTables());sync()}const added={};for(const[,table]of actions)added[table]=(state.tables[table]||[]).filter(r=>!before[table]?.has(String(r.id)));return{added}}finally{state.busy=false}}

function focusMeeting(id){requestAnimationFrame(()=>{const c=ui.list.querySelector(`[data-meeting-id="${CSS.escape(String(id))}"]`);if(c){c.classList.add("meeting-card--highlight");c.scrollIntoView({block:"nearest",behavior:"smooth"});setTimeout(()=>c.classList.remove("meeting-card--highlight"),1800)}})}
function feedback(m){ui.feedback.textContent=m;ui.feedback.hidden=false;setTimeout(()=>ui.feedback.hidden=true,4000)}function showState(t,m){ui.content.hidden=true;const b=element("div");b.append(textElement("strong",t),textElement("p",m));ui.state.replaceChildren(b);ui.state.hidden=false}
const peopleValue=v=>referenceIds(v).map(id=>person(id)?personLabel(person(id)):id).join(", "),referenceIds=v=>!hasValue(v)?[]:(Array.isArray(v)?v.flat(3):[v]).filter(x=>x!=="L"&&hasValue(x)).map(String),same=(a,b)=>String(a)===String(b),startToday=()=>{const d=new Date;d.setHours(0,0,0,0);return d.getTime()},isUpcoming=m=>dateValue(m.Date_reunion??m.Date)>=startToday();
function dateValue(v){if(!hasValue(v))return 0;const d=new Date(typeof v==="number"?v*1000:v);return Number.isNaN(d.getTime())?0:d.getTime()}function formatDate(v){const t=dateValue(v);return t?new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date(t)):""}const inputDate=v=>dateValue(v)?new Date(dateValue(v)).toISOString().slice(0,10):"",hasValue=v=>v!==null&&v!==undefined&&String(v).trim()!=="",displayValue=v=>Array.isArray(v)?v.filter(x=>x!=="L").map(displayValue).join(", "):hasValue(v)?String(v).trim():"",textOr=(v,f)=>hasValue(v)?displayValue(v):f,normalizeText=v=>displayValue(v).toLocaleLowerCase("fr-FR").normalize("NFD").replace(/[\u0300-\u036f]/g,""),isTrue=v=>v===true||v===1||["true","vrai","oui","1"].includes(normalizeText(v)),exactError=e=>e instanceof Error?`${e.name} : ${e.message}`:String(e);
function statusKind(v){const t=normalizeText(v);return/(fait|realise|termine|valide)/.test(t)?"success":/(retard|bloque|annule)/.test(t)?"danger":/(arbitr|decid)/.test(t)?"arbitration":"info"}function badge(v,k){return textElement("span",v,`badge badge--${k}`)}function option(v,l){const o=element("option");o.value=v;o.textContent=l;return o}function element(tag,cls){const n=document.createElement(tag);if(cls)n.className=cls;return n}function textElement(tag,v,cls){const n=element(tag,cls);n.textContent=displayValue(v);return n}
const renderMeetingsView = render;
render = function renderWithProjectReturn() {
  renderMeetingsView();
  window.PilotageContext?.configureProjectReturn(document.querySelector("#project-return"), state.project);
};

initialize();
