"use strict";
const EXPECTED={
  PROJETS:{Nom_projet:"Text",Statut:{type:"Choice",choices:["À venir","En cours","Terminé","Abandonné"]},Thematiques:"ChoiceList",Services_concernes:"RefList:SERVICES",Elu_pilote:"Ref:INTERLOCUTEURS",Agent_pilote:"Ref:INTERLOCUTEURS",Elus_associes:"RefList:INTERLOCUTEURS",Agents_associes:"RefList:INTERLOCUTEURS",Interlocuteurs_externes:"RefList:INTERLOCUTEURS",Mois_lancement:"Choice",Annee_lancement:"Int",Trimestre_objectif:"Choice",Annee_objectif:"Int",Motif_abandon:"Text",Date_cloture:"DateTime"},
  INTERLOCUTEURS:{Nom_complet:"Text",Interne_Mairie:"Bool",Role_interne:"Choice",Actif:"Bool"},
  SERVICES:{Nom_service:"Text",Actif:"Bool"},
  ACTIONS:{Projet:"Ref:PROJETS",Action:"Text",Statut:{type:"Choice",choices:["À attribuer","À faire","En cours","Réalisée","Non aboutie"]},Demandee_par:"Ref:INTERLOCUTEURS",Attribuee_a:"Ref:INTERLOCUTEURS",Service_destinataire:"Ref:SERVICES",Echeance:"Date",Date_fin:"Date",Resultat:"Text",Raison_non_aboutie:"Text",Reunion_origine:"Ref:REUNIONS"},
  CONSIGNES_POLITIQUES:{Projet:"Ref:PROJETS",Consigne:"Text",Emetteur:"Ref:INTERLOCUTEURS",Destinataires:"RefList:INTERLOCUTEURS",Services_destinataires:"RefList:SERVICES",Statut:{type:"Choice",choices:["Active","Archivée"]},Date_emission:"Date",Date_archivage:"Date",Motif_archivage:"Text"},
  ARBITRAGES_DECISIONS:{Projet:"Ref:PROJETS",Sujet:"Text",Question_a_trancher:"Text",Statut:"Choice",Reunion_origine:"Ref:REUNIONS"},
  REUNIONS:{Projet:"Ref:PROJETS",Date_reunion:"DateTime",Objet:"Text",Participants:"RefList:INTERLOCUTEURS",Compte_rendu:"Text",Points_cles:"Text"},
  JALONS:{Projet:"Ref:PROJETS",Jalon:"Text",Ordre:"Int",Date_prevue:"Date",Franchi:"Bool",Date_reelle:"Date",A_retenir:"Text",Reunion_origine:"Ref:REUNIONS"},
  BLOCAGES:{Projet:"Ref:PROJETS",Blocage:"Text",Date_apparition:"DateTime",Actif:"Bool",Date_resolution:"DateTime",Explication_resolution:"Text",Reunion_origine:"Ref:REUNIONS"},
  VIGILANCES:{Projet:"Ref:PROJETS",Vigilance:"Text",Date_apparition:"DateTime",Active:"Bool",Date_resolution:"DateTime",Explication_resolution:"Text",Reunion_origine:"Ref:REUNIONS"},
  ATTENTES_EXTERNES:{Projet:"Ref:PROJETS",Attente:"Text",Tiers:"Ref:INTERLOCUTEURS",Date_attendue:"Date",Statut:{type:"Choice",choices:["En attente","Reçue","Sans suite"]},Date_fin:"DateTime",Resultat:"Text",Blocage:"Ref:BLOCAGES",Reunion_origine:"Ref:REUNIONS"},
  RELANCES_ATTENTES:{Attente:"Ref:ATTENTES_EXTERNES",Date_relance:"DateTime",Note:"Text"},
  REUNIONS_VERSIONS:{Reunion:"Ref:REUNIONS",Numero_version:"Int",Compte_rendu:"Text",Points_cles:"Text",Auteur:"Ref:INTERLOCUTEURS",Date_version:"DateTime",Motif_modification:"Text",Demandeur:"Ref:INTERLOCUTEURS",Approbateur:"Ref:INTERLOCUTEURS",Statut_demande:{type:"Choice",choices:["Approuvée"]}},
  AVANCEMENTS:{Projet:"Ref:PROJETS",Date_evenement:"DateTime",Type_entree:{type:"Choice",choices:["Avancement","Information","Changement de pilote","Changement d’objectif","Changement de statut","Clôture du projet","Réouverture du projet","Jalon franchi","Blocage levé","Vigilance levée","Décision prise"]},Titre:"Text",Description:"Text",Source_table:"Text",Source_id:"Int",Automatique:"Bool"}
};
const LEGACY={PROJETS:["Pourcentage_avancement","Avancement","Priorite","Categorie"],ACTIONS:["Priorite","Type_action","Controle","Commentaire"],CONSIGNES_POLITIQUES:["Priorite","Echeance","Controle","Retour"],REUNIONS:["Type_reunion","CR_finalise","Decisions_prises","Suites","Actions","Engagements","Arbitrage_attendu"]};
const $=selector=>document.querySelector(selector),ui={state:$("#state"),content:$("#content"),summary:$("#summary"),results:$("#results"),legacy:$("#legacy-list"),run:$("#run"),export:$("#export"),verdict:document.querySelector(".verdict"),verdictTitle:$("#verdict-title"),verdictText:$("#verdict-text")};
let currentSchema=null;
ui.run.addEventListener("click",run);ui.export.addEventListener("click",exportSchema);run();
async function run(){ui.run.disabled=true;ui.export.hidden=true;ui.content.hidden=true;ui.state.hidden=false;try{if(!window.grist?.docApi)throw Error("Ouvrez cette page comme widget personnalisé dans le document Grist à contrôler.");await Promise.resolve(window.grist.ready({requiredAccess:"read table"}));const schema=await readSchema(),checks=checkSchema(schema);currentSchema=schema;render(checks,schema);ui.export.hidden=false}catch(error){currentSchema=null;showError(error)}finally{ui.run.disabled=false}}
async function readSchema(){const[tablesRaw,columnsRaw]=await Promise.all([window.grist.docApi.fetchTable("_grist_Tables"),window.grist.docApi.fetchTable("_grist_Tables_column")]),tables=columnar(tablesRaw),columns=columnar(columnsRaw),ids=new Map(tables.map(row=>[String(row.id),row.tableId]));return Object.fromEntries(tables.map(table=>[table.tableId,Object.fromEntries(columns.filter(column=>ids.get(String(column.parentId))===table.tableId).map(column=>[column.colId,{label:String(column.label||""),type:String(column.type||""),formula:String(column.formula||""),isFormula:Boolean(column.isFormula),recalcWhen:Number(column.recalcWhen)||0,recalcDeps:decodeValue(column.recalcDeps),choices:choices(column.widgetOptions)}]))]))}
function exportSchema(){if(!currentSchema)return;const payload={format:"pilotage-grist-schema-v3",exportedAt:new Date().toISOString(),containsBusinessRows:false,tables:currentSchema},blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`schema-grist-v3-${new Date().toISOString().slice(0,10)}.json`;document.body.append(link);link.click();link.remove();URL.revokeObjectURL(url)}
function checkSchema(schema){const out=[];for(const[table,columns]of Object.entries(EXPECTED)){if(!schema[table]){out.push({level:"error",title:`Table manquante : ${table}`,detail:"Créer cette table avant la recette complète de la V3."});continue}for(const[name,rule]of Object.entries(columns)){const column=schema[table][name];if(!column){out.push({level:"error",title:`${table}.${name} est absente`,detail:`Créer la colonne avec le type ${ruleType(rule)}.`});continue}const expected=ruleType(rule);if(!sameType(column.type,expected))out.push({level:"error",title:`Type incorrect : ${table}.${name}`,detail:`Type reçu : ${column.type||"vide"}. Type attendu : ${expected}.`});if(column.formula)out.push({level:"warning",title:`Colonne calculée : ${table}.${name}`,detail:"Le widget doit pouvoir écrire dans cette colonne ; vérifier si la formule est intentionnelle."});if(rule.choices){const missing=rule.choices.filter(choice=>!column.choices.includes(choice));if(missing.length)out.push({level:"error",title:`Choix incomplets : ${table}.${name}`,detail:`Ajouter exactement : ${missing.join(", ")}.`})}}}return out}
function render(checks,schema){const errors=checks.filter(item=>item.level==="error").length,warnings=checks.filter(item=>item.level==="warning").length,valid=Object.keys(EXPECTED).length-errors;ui.summary.replaceChildren(summaryCard("Tables contrôlées",Object.keys(EXPECTED).length),summaryCard("Blocages",errors),summaryCard("Avertissements",warnings));ui.verdict.className=`card verdict ${errors?"verdict--danger":"verdict--success"}`;ui.verdictTitle.textContent=errors?"Schéma non prêt pour la publication":"Schéma prêt pour la recette fonctionnelle";ui.verdictText.textContent=errors?`${errors} correction${errors>1?"s sont":" est"} nécessaire${errors>1?"s":""}. La V3 ne doit pas être publiée avant leur résolution.`:"Aucun blocage structurel détecté. Exécutez maintenant la checklist fonctionnelle dans PUBLICATION-V3.md.";ui.results.replaceChildren(...(checks.length?checks:[resultCard({level:"success",title:"Tous les contrôles structurels sont satisfaits",detail:`${valid} ensembles de tables ont été vérifiés.`})]));const found=[];for(const[table,names]of Object.entries(LEGACY))for(const name of names)if(schema[table]?.[name])found.push(`${table}.${name}`);ui.legacy.replaceChildren(...(found.length?found.map(name=>{const li=document.createElement("li");li.textContent=name;return li}):[textElement("li","Aucune colonne ancienne connue n’a été détectée.")]));ui.state.hidden=true;ui.content.hidden=false}
function resultCard(item){const card=document.createElement("article"),mark=textElement("span",item.level==="error"?"✕":item.level==="warning"?"!":"✓","result__mark"),body=document.createElement("div");card.className=`card result result--${item.level}`;body.append(textElement("h3",item.title),textElement("p",item.detail));card.append(mark,body);return card}
function summaryCard(label,value){const card=document.createElement("article");card.className="card summary-card";card.append(textElement("span",label),textElement("strong",value));return card}
function columnar(value){const names=Object.keys(value||{}).filter(name=>Array.isArray(value[name])),length=Math.max(0,...names.map(name=>value[name].length));return Array.from({length},(_,index)=>Object.fromEntries(names.map(name=>[name,value[name][index]])))}
function choices(raw){try{const value=typeof raw==="string"?JSON.parse(raw):raw;return Array.isArray(value?.choices)?value.choices:[]}catch{return[]}}
function decodeValue(raw){if(raw===null||raw===undefined||raw==="")return null;if(typeof raw!=="string")return raw;try{return JSON.parse(raw)}catch{return raw}}
function ruleType(rule){return typeof rule==="string"?rule:rule.type}function sameType(actual,expected){const received=actual.toLowerCase(),wanted=expected.toLowerCase();return received===wanted||(wanted==="datetime"&&received.startsWith("datetime:"))}function textElement(tag,text,className=""){const node=document.createElement(tag);node.textContent=String(text);if(className)node.className=className;return node}function showError(error){ui.state.replaceChildren(textElement("strong","Diagnostic impossible"),textElement("p",error instanceof Error?error.message:String(error)));ui.state.hidden=false}
