"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.join(__dirname,"..");
function load(page="fiche-projet",search="",store=new Map(),demo=false){
 const window={location:{href:"https://tride40.github.io/pilotage-grist/"+page+"/"+search,pathname:"/pilotage-grist/"+page+"/",search},self:{},top:{}};if(demo)window.self=window.top;
 const storage={getItem:key=>store.get(key),setItem:(key,value)=>store.set(key,value),removeItem:key=>store.delete(key)};
 const sandbox={window,URL,URLSearchParams,Date,sessionStorage:storage,localStorage:storage};
 for(const file of ["navigation.js","context.js"])vm.runInNewContext(fs.readFileSync(path.join(__dirname,file),"utf8"),sandbox);return window;
}
test("destinations éditables en page seule",()=>{const nav=load().PilotageNavigation;for(const [page,id]of Object.entries({home:16,dashboard:9,project:10,meetings:11,actions:37,contacts:14,weekly:15})){const url=new URL(nav.pageUrl(page));assert.ok(url.pathname.endsWith("/p/"+id));assert.equal(url.searchParams.get("style"),"singlePage");assert.equal(url.searchParams.has("embed"),false);}assert.throws(()=>nav.pageUrl("unknown"));});
test("paramètres et liens externes conservés",()=>{const nav=load().PilotageNavigation,url=new URL(nav.applicationUrl(nav.pageUrl("project")+"&embed=true&x=42#row17"));assert.equal(url.searchParams.get("x"),"42");assert.equal(url.hash,"#row17");assert.equal(url.searchParams.has("embed"),false);assert.equal(nav.applicationUrl(url.href),url.href);for(const link of ["https://example.org/","mailto:contact@example.org","https://grist.numerique.gouv.fr/other-document"])assert.equal(nav.applicationUrl(link),link);});
test("outils ouverts dans Grist",()=>{const ctx=load().PilotageContext;assert.match(ctx.projectToolUrl("actions",42),/\/p\/37\?style=singlePage$/);assert.match(ctx.projectToolUrl("meetings",42),/\/p\/11\?style=singlePage$/);assert.match(ctx.projectPageUrl(42),/\/p\/10\?style=singlePage$/);});
test("projet transmis aux réunions une seule fois",()=>{const store=new Map();load("fiche-projet","",store).PilotageContext.rememberToolProject("meetings",{id:42});const ctx=load("reunions","",store).PilotageContext;assert.equal(ctx.projectId,"42");assert.equal(ctx.isProjectMode,true);const link={};assert.equal(ctx.configureProjectReturn(link,{id:42}),true);assert.match(link.href,/\/p\/10\?style=singlePage$/);assert.equal(load("reunions","",store).PilotageContext.projectId,"");});
test("expiration et démonstration",()=>{const store=new Map([["pilotage-grist:meeting-navigation",JSON.stringify({id:42,at:Date.now()-120000})]]);assert.equal(load("reunions","",store).PilotageContext.projectId,"");const ctx=load("fiche-projet","?demo=1",new Map(),true).PilotageContext,url=new URL(ctx.projectToolUrl("meetings",42));assert.equal(url.hostname,"tride40.github.io");assert.equal(url.searchParams.get("demo"),"1");assert.equal(url.searchParams.get("projectId"),"42");});
test("module et retours Accueil dans toutes les pages actives",()=>{for(const file of ["accueil/index.html","dashboard/index.html","fiche-projet/index.html","reunions/index.html","interlocuteurs/index.html","point-hebdomadaire/index.html","actions/actions.html","utilisateurs-acces/index.html"]){const html=fs.readFileSync(path.join(root,file),"utf8");assert.match(html,/navigation\.js\?v=1/,file);if(!file.startsWith("accueil/")&&!file.startsWith("actions/"))assert.match(html,/\/p\/16\?style=singlePage" target="_top"/,file);for(const [,href]of html.matchAll(/href="(https:\/\/grist[^" ]+)"/g))assert.equal(new URL(href).searchParams.get("style"),"singlePage",file);}assert.match(fs.readFileSync(path.join(root,"actions/actions-app.js"),"utf8"),/PilotageNavigation\.pageUrl\("home"\)/);});
