"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),rules=require("./v3-rules.js");
test("un projet À venir peut rester incomplet",()=>assert.deepEqual(rules.projectErrors({Statut:"À venir"}),[]));
test("un projet En cours exige les deux pilotes",()=>assert.equal(rules.projectErrors({Statut:"En cours"}).length,2));
test("l’ancien Responsable reste un repli de migration",()=>assert.deepEqual(rules.projectErrors({Statut:"En cours",Elu_pilote:2,Responsable:3}),[]));
test("un abandon exige un motif",()=>assert.equal(rules.projectErrors({Statut:"Abandonné"})[0],"Le motif d’abandon est obligatoire."));
test("les changements structurants sont regroupés pour le journal",()=>{const changes=rules.projectJournalChanges({Elu_pilote:1,Agent_pilote:2,Trimestre_objectif:"T2",Annee_objectif:2027},{Elu_pilote:3,Agent_pilote:2,Trimestre_objectif:"T3",Annee_objectif:2028});assert.deepEqual(changes,[{type:"Changement de pilote",fields:["Elu_pilote"]},{type:"Changement d’objectif",fields:["Trimestre_objectif","Annee_objectif"]}])});
test("le repli Responsable ne produit pas de faux changement d’agent",()=>assert.deepEqual(rules.projectJournalChanges({Responsable:2},{Agent_pilote:2}),[]));
test("un ancien Responsable ne masque pas la suppression du nouvel agent pilote",()=>{assert.equal(rules.projectErrors({Statut:"En cours",Elu_pilote:1,Agent_pilote:null,Responsable:2})[0],"Désignez un Agent pilote avant de passer le projet à En cours.");assert.equal(rules.projectJournalChanges({Agent_pilote:2,Responsable:2},{Agent_pilote:null,Responsable:2})[0].type,"Changement de pilote")});
test("les projets clos sortent du pilotage",()=>{assert.equal(rules.isProjectActive({Statut:"Terminé"}),false);assert.equal(rules.isProjectActive({Statut:"En cours"}),true)});
test("seuls les statuts V3 ferment une action",()=>{assert.equal(rules.isActionClosed({Statut:"Réalisée"}),true);assert.equal(rules.isActionClosed({Statut:"En cours"}),false)});
