"use strict";
const TABLE="ACTIONS",REQUIRED_TABLES=["PROJETS",TABLE,"INTERLOCUTEURS"],READ_ONLY_COLUMNS=new Set(["En_retard","A_controler"]);
const STATUS={todo:"À faire",progress:"En cours",done:"Réalisée",cancelled:"Annulée",check:"À contrôler",controlled:"Contrôlée",revise:"À reprendre"};
const state={projects:[],actions:[],people:[],meetings:[],columns:new Set(),project:null,demo:false,busy:false,includeMeetings:false,sort:"due"};
const ui={interfaceState:document.querySelector("#interface-state"),content:document.querySelector("#actions-content"),feedback:document.querySelector("#feedback"),selector:document.querySelector("#project-selector"),contextLabel:document.querySelector("#context-label"),contextProject:document.querySelector("#context-project"),sort:document.querySelector("#action-sort"),openCreate:document.querySelector("#open-create"),dialog:document.querySelector("#action-dialog"),form:document.querySelector("#action-form"),summary:document.querySelector("#summary"),sections:Object.fromEntries([...document.querySelectorAll("[data-section]")].map(section=>[section.dataset.section,{list:section.querySelector("[data-list]"),count:section.querySelector("[data-count]")}]))};

async function initialize(){bindControls();try{if(isDemoMode()){state.demo=true;state.includeMeetings=true;applyTables(window.ACTIONS_DEMO_DATA.tables);return}if(!window.grist?.docApi)throw new Error("L’API Grist n’est pas disponible.");await withTimeout(Promise.resolve(window.grist.ready({requiredAccess:"full"})),"initialisation de l’API Grist");const tableNames=normalizeTableNames(await withTimeout(window.grist.docApi.listTables(),"détection des tables")),missing=REQUIRED_TABLES.filter(name=>!tableNames.includes(name));if(missing.length)throw new Error(`Tables Grist introuvables : ${missing.join(", ")}.`);state.includeMeetings=tableNames.includes("REUNIONS");await reloadTables();window.grist.onRecord(record=>{const project=record&&state.projects.find(item=>String(item.id)===String(record.id));if(project){state.project=project;ui.selector.value=String(project.id);render()}})}catch(error){showFatal("Connexion à Grist impossible",exactError(error))}}
async function reloadTables(preferredProjectId=state.project?.id){const names=[...REQUIRED_TABLES,...(state.includeMeetings?["REUNIONS"]:[])],entries=await Promise.all(names.map(async name=>{const raw=await withTimeout(window.grist.docApi.fetchTable(name),`lecture de ${name}`);if(name===TABLE)state.columns=new Set(Object.keys(raw).filter(key=>Array.isArray(raw[key])));return[name,columnarToRecords(raw)]}));applyTables(Object.fromEntries(entries),preferredProjectId)}
function applyTables(tables,preferredProjectId){state.projects=tables.PROJETS||[];state.actions=tables.ACTIONS||[];state.people=tables.INTERLOCUTEURS||[];state.meetings=tables.REUNIONS||[];if(state.demo)state.columns=new Set(Object.keys(state.actions[0]||{}));populateSelectors();state.project=window.PilotageContext?.selectProject(state.projects,preferredProjectId,firstActiveProject)||state.projects.find(item=>String(item.id)===String(preferredProjectId))||firstActiveProject();render()}
function populateSelectors(){const projects=[...state.projects].sort((a,b)=>textOr(a.Nom_projet,"").localeCompare(textOr(b.Nom_projet,""),"fr"));ui.selector.replaceChildren(...projects.map(project=>option(project.id,textOr(project.Nom_projet,"Projet sans nom"))));ui.selector.disabled=!projects.length||Boolean(window.PilotageContext?.isProjectMode);populatePeople("")}
function populatePeople(query){const normalized=normalizeText(query),people=[...state.people].filter(person=>normalizeText([personName(person),person.Organisme,person.Fonction].filter(hasValue).join(" ")).includes(normalized)).sort((a,b)=>personName(a).localeCompare(personName(b),"fr"));for(const [name,empty] of [["Demandee_par","Non renseigné"],["Responsable","Non attribuée"]]){const control=ui.form.elements[name];if(!control)continue;const selected=control.value;control.replaceChildren(option("",empty),...people.map(person=>option(person.id,personName(person))));if([...control.options].some(item=>item.value===selected))control.value=selected}}

function render(){if(!state.project){showFatal("Aucun projet disponible","Ajoutez un projet dans la table PROJETS.");return}ui.selector.value=String(state.project.id);if(ui.contextLabel)ui.contextLabel.textContent=window.PilotageContext?.isProjectMode?"Projet imposé":"Vue globale";if(ui.contextProject)ui.contextProject.textContent=textOr(state.project.Nom_projet,"Projet");const groups={todo:[],progress:[],overdue:[],check:[],history:[]};state.actions.filter(row=>referenceIds(row.Projet).includes(String(state.project.id))).forEach(row=>groups[classify(row)].push(row));for(const key of Object.keys(groups))groups[key].sort(compareActions);const empty={todo:"Aucune action à lancer.",progress:"Aucune action en cours.",overdue:"Aucune action en retard.",check:"Aucune action n’attend de contrôle.",history:"Aucune action dans l’historique."};Object.keys(groups).forEach(key=>renderGroup(key,groups[key],empty[key]));renderSummary(groups);ui.interfaceState.hidden=true;ui.interfaceState.style.display="none";ui.content.hidden=false;ui.openCreate.disabled=state.busy}
function renderSummary(groups){const entries=[["À faire",groups.todo.length],["En cours",groups.progress.length],["En retard",groups.overdue.length],["À contrôler",groups.check.length],["Historique",groups.history.length]];ui.summary.replaceChildren(...entries.map(([label,value])=>{const item=element("div","summary__item");item.append(textElement("strong",value,"summary__value"),textElement("span",label,"summary__label"));return item}))}
function renderGroup(key,rows,emptyText){const section=ui.sections[key];section.count.textContent=String(rows.length);section.list.replaceChildren(...(rows.length?rows.map(row=>renderCard(row,key)):[textElement("p",emptyText,"empty-state")]))}
function renderCard(row,group){const cancelled=normalizeText(row.Statut).includes("annul"),card=element("article",`card action-card action-card--${group}${cancelled?" action-card--cancelled":""}`),header=element("header","action-card__header");header.append(textElement("h3",textOr(row.Action,"Action sans intitulé"),"action-card__title"));const badges=element("div","action-card__badges");if(group!=="history")badges.append(makeBadge(textOr(row.Priorite,"Priorité normale"),priorityKind(row.Priorite)));badges.append(makeBadge(textOr(row.Statut,statusLabel(group)),statusKind(group,row)));if(isTrue(row.Controle_requis))badges.append(makeBadge("Contrôle requis","arbitration"));if(isTrue(row.En_retard)||group==="overdue")badges.append(makeBadge("En retard","danger"));header.append(badges);card.append(header);const meta=element("dl","action-card__meta");appendOptionalDefinition(meta,"Demandée par",personValue(row.Demandee_par));appendOptionalDefinition(meta,"Attribuée à",personValue(row.Responsable));appendOptionalDefinition(meta,"Mode",row.Nature_action);appendOptionalDefinition(meta,"Type",row.Type_action);appendOptionalDefinition(meta,"Créée le",formatDate(row.Date_creation));appendOptionalDefinition(meta,"Échéance",formatDate(row.Echeance),group==="overdue"?"is-overdue":"");if(group==="history")appendOptionalDefinition(meta,"Réalisée le",formatDate(row.Date_realisation));appendOptionalDefinition(meta,"Origine",meetingValue(row.Reunion||row.Origine_reunion||row.Reunion_origine));card.append(meta);const notes=element("div","action-card__notes");if(group==="history"||group==="check")appendNote(notes,"Résultat",row.Resultat);appendNote(notes,"Commentaire",row.Commentaire);if(notes.childElementCount)card.append(notes);if(group!=="history")card.append(renderEditor(row,group));return card}
function renderEditor(row,group){const editor=element("div","action-card__editor"),fields=element("div","inline-fields"),statusWrapper=element("label","form-field");statusWrapper.append(textElement("span","Statut","form-field__label"));const statusSelect=element("select","form-field__control");[STATUS.todo,STATUS.progress,STATUS.revise].forEach(value=>statusSelect.append(option(value,value)));statusSelect.value=knownEditableStatus(row.Statut);statusWrapper.append(statusSelect);const result=textareaField("Résultat",row.Resultat,"Décrivez le résultat obtenu…"),comment=textareaField("Commentaire",row.Commentaire,"Ajoutez un point de suivi…");result.label.hidden=true;fields.append(statusWrapper,result.label,comment.label);editor.append(fields);const actions=element("div","action-card__actions");actions.append(actionButton("Enregistrer","secondary",()=>saveAction(row,statusSelect.value,undefined,comment.input.value)));if(group!=="check"){const doneButton=actionButton("Réalisée","success",()=>{if(result.label.hidden){result.label.hidden=false;doneButton.textContent="Confirmer la clôture";result.input.focus();return}markDone(row,result.input.value,comment.input.value)});actions.append(doneButton,actionButton("Annulée","danger",()=>cancelAction(row,"",comment.input.value)))}if(group==="check")actions.append(actionButton("Valider le contrôle","primary",()=>controlAction(row,true,comment.input.value)),actionButton("À reprendre","secondary",()=>controlAction(row,false,comment.input.value)));editor.append(actions);return editor}

async function createAction(formData){const fields=writableFields({Projet:Number(state.project.id),Action:formData.get("Action").trim(),Demandee_par:optionalNumber(formData.get("Demandee_par")),Responsable:optionalNumber(formData.get("Responsable")),Nature_action:formData.get("Nature_action"),Type_action:formData.get("Type_action"),Priorite:formData.get("Priorite"),Statut:STATUS.todo,Date_creation:nowGrist(),Echeance:gristDate(formData.get("Echeance")),Controle_requis:formData.get("Controle_requis")==="on",Controle_effectue:false});requireFields(fields,["Projet","Action"]);await writeAction(["AddRecord",TABLE,null,fields],"Action créée.");ui.form.reset();populatePeople("");ui.dialog.close()}
async function saveAction(row,status,result,comment){if(status===STATUS.done){await markDone(row,result||"",comment);return}const fields=writableFields({Statut:status,Resultat:result===undefined?undefined:result.trim(),Commentaire:comment.trim()});requireAnyField(fields);await writeAction(["UpdateRecord",TABLE,row.id,fields],status===STATUS.cancelled?"Action annulée et déplacée dans l’historique.":"Action mise à jour.")}
async function markDone(row,result,comment){const requiresControl=isTrue(row.Controle_requis),fields=writableFields({Statut:requiresControl?STATUS.check:STATUS.done,Date_realisation:nowGrist(),Resultat:result.trim(),Commentaire:comment.trim(),Controle_effectue:requiresControl?false:row.Controle_effectue});requireFields(fields,["Statut"]);await writeAction(["UpdateRecord",TABLE,row.id,fields],requiresControl?"Action réalisée : elle attend le contrôle de l’élu.":"Action marquée comme réalisée.")}
async function cancelAction(row,result,comment){const fields=writableFields({Statut:STATUS.cancelled,Resultat:result.trim(),Commentaire:comment.trim()});requireFields(fields,["Statut"]);await writeAction(["UpdateRecord",TABLE,row.id,fields],"Action annulée et déplacée dans l’historique.")}
async function controlAction(row,validated,comment){const fields=writableFields({Statut:validated?STATUS.controlled:STATUS.revise,Controle_effectue:validated,Commentaire:comment.trim()});requireFields(fields,["Statut"]);if(validated&&state.columns.has("Controle_effectue"))requireFields(fields,["Controle_effectue"]);await writeAction(["UpdateRecord",TABLE,row.id,fields],validated?"Contrôle validé.":"Action renvoyée pour reprise.")}
async function writeAction(action,successMessage){if(state.busy)return;state.busy=true;setInteractiveDisabled(true);try{if(state.demo)applyDemoAction(action);else await withTimeout(window.grist.docApi.applyUserActions([action]),"écriture dans Grist");if(state.demo)render();else await reloadTables(state.project.id);showFeedback(successMessage)}catch(error){showFeedback(`Écriture impossible — ${exactError(error)}`,true)}finally{state.busy=false;setInteractiveDisabled(false)}}
function applyDemoAction([type,,id,fields]){if(type==="AddRecord")state.actions.push({id:Math.max(0,...state.actions.map(row=>Number(row.id)||0))+1,...fields,En_retard:false,A_controler:false});else{const row=state.actions.find(item=>String(item.id)===String(id));Object.assign(row,fields);row.En_retard=computedOverdue(row);row.A_controler=isTrue(row.Controle_requis)&&isDoneLike(row)&&!isTrue(row.Controle_effectue)}}
function bindControls(){ui.selector.addEventListener("change",()=>{state.project=state.projects.find(project=>String(project.id)===ui.selector.value)||null;render()});ui.sort?.addEventListener("change",()=>{state.sort=ui.sort.value;render()});ui.openCreate.addEventListener("click",()=>{ui.form.reset();populatePeople("");ui.form.elements.Action.value="";ui.dialog.showModal();ui.form.elements.Action.focus()});ui.form.elements.people_search?.addEventListener("input",event=>populatePeople(event.target.value));ui.dialog.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",()=>ui.dialog.close()));ui.dialog.addEventListener("click",event=>{if(event.target===ui.dialog)ui.dialog.close()});ui.form.addEventListener("submit",async event=>{event.preventDefault();if(!ui.form.reportValidity())return;try{await createAction(new FormData(ui.form))}catch(error){showFeedback(exactError(error),true)}})}

function classify(row){if((isTrue(row.A_controler)&&isDoneLike(row))||(isTrue(row.Controle_requis)&&isDoneLike(row)&&!isTrue(row.Controle_effectue))||normalizeText(row.Statut).includes("controler"))return"check";if(isHistory(row))return"history";if(isTrue(row.En_retard)||computedOverdue(row))return"overdue";return normalizeText(row.Statut).includes("cours")||normalizeText(row.Statut).includes("reprendre")?"progress":"todo"}
function isHistory(row){const status=normalizeText(row.Statut);return isTrue(row.Controle_effectue)||["realisee","terminee","controlee","validee","archivee","annulee"].some(value=>status.includes(value))}
function isDoneLike(row){return Boolean(dateValue(row.Date_realisation))||["realisee","terminee","controle","validee"].some(value=>normalizeText(row.Statut).includes(value))}
function computedOverdue(row){const due=dateValue(row.Echeance);return due>0&&due<startOfToday()&&!isDoneLike(row)}
function writableFields(values){return Object.fromEntries(Object.entries(values).filter(([key,value])=>state.columns.has(key)&&!READ_ONLY_COLUMNS.has(key)&&value!==null&&value!==undefined))}
function requireFields(fields,names){const missing=names.filter(name=>!Object.hasOwn(fields,name));if(missing.length)throw new Error(`Colonnes obligatoires absentes : ${missing.join(", ")}.`)}function requireAnyField(fields){if(!Object.keys(fields).length)throw new Error("Aucune colonne modifiable compatible n’a été trouvée dans ACTIONS.")}
function firstActiveProject(){return state.projects.find(project=>!isTrue(project.Archive)&&!["termine","abandonne"].includes(normalizeText(project.Statut)))||state.projects[0]||null}
function personValue(value){return referenceIds(value).map(id=>personName(state.people.find(person=>String(person.id)===id))||id).join(", ")}function personName(person){return person?textOr(person.Nom_complet||[person.Prenom,person.Nom].filter(hasValue).join(" "),"Interlocuteur sans nom"):""}
function meetingValue(value){return referenceIds(value).map(id=>{const meeting=state.meetings.find(item=>String(item.id)===id);return meeting?`${formatDate(meeting.Date_reunion||meeting.Date)} — ${textOr(meeting.Objet,"Réunion")}`:""}).filter(Boolean).join(", ")}function referenceIds(value){const values=Array.isArray(value)?value:[value];return values.filter(item=>item!=="L"&&hasValue(item)&&Number(item)!==0).map(String)}function compareDueDates(a,b){return(dateValue(a.Echeance)||Infinity)-(dateValue(b.Echeance)||Infinity)}function compareActions(a,b){if(state.sort==="priority")return priorityScore(b.Priorite)-priorityScore(a.Priorite)||compareDueDates(a,b);if(state.sort==="created")return dateValue(b.Date_creation)-dateValue(a.Date_creation)||compareDueDates(a,b);return compareDueDates(a,b)}function priorityScore(value){const text=normalizeText(value);return text.includes("urgent")?4:text.includes("priorit")?3:text.includes("haut")?2:text.includes("normal")?1:0}
function priorityKind(value){const text=normalizeText(value);return text.includes("urgent")?"danger":text.includes("haut")?"warning":"info"}function statusKind(group,row){return normalizeText(row?.Statut).includes("annul")?"danger":group==="history"?"success":group==="check"?"arbitration":group==="overdue"?"danger":"info"}function statusLabel(group){return({todo:STATUS.todo,progress:STATUS.progress,overdue:"En retard",check:STATUS.check,history:"Terminée"})[group]}function knownEditableStatus(value){const normalized=normalizeText(value);return normalized.includes("annul")?STATUS.cancelled:normalized.includes("realis")?STATUS.done:normalized.includes("reprendre")?STATUS.revise:normalized.includes("cours")?STATUS.progress:STATUS.todo}
function textareaField(label,value,placeholder){const wrapper=element("label","form-field");wrapper.append(textElement("span",label,"form-field__label"));const input=element("textarea","form-field__control");input.value=displayValue(value);input.placeholder=placeholder;wrapper.append(input);return{label:wrapper,input}}function appendDefinition(container,label,value,className=""){const wrapper=element("div",className);wrapper.append(textElement("dt",label),textElement("dd",value));container.append(wrapper)}function appendOptionalDefinition(container,label,value,className=""){if(hasValue(value))appendDefinition(container,label,value,className)}function appendNote(container,label,value){if(!hasValue(value))return;const note=element("section","action-card__note");note.append(textElement("strong",label),textElement("p",value));container.append(note)}
function makeBadge(value,kind){return textElement("span",value,`badge badge--${kind}`)}function actionButton(label,kind,handler){const button=textElement("button",label,`button button--${kind}`);button.type="button";button.addEventListener("click",()=>Promise.resolve().then(handler).catch(error=>showFeedback(exactError(error),true)));return button}function option(value,label){const node=element("option");node.value=String(value);node.textContent=label;return node}
function setInteractiveDisabled(disabled){document.querySelectorAll("button, textarea, select, input").forEach(control=>{control.disabled=disabled})}function showFeedback(message,error=false){ui.feedback.textContent=message;ui.feedback.className=`feedback${error?" feedback--error":""}`;ui.feedback.hidden=false;window.setTimeout(()=>{ui.feedback.hidden=true},6000)}function showFatal(title,message){ui.content.hidden=true;ui.interfaceState.replaceChildren(textElement("strong",title),textElement("p",message));ui.interfaceState.style.display="";ui.interfaceState.hidden=false}
function normalizeTableNames(value){const rows=Array.isArray(value)?value:Array.isArray(value?.tables)?value.tables:[];return rows.map(row=>typeof row==="string"?row:row?.id??row?.tableId??row?.name??"").filter(Boolean)}function columnarToRecords(columns){const names=Object.keys(columns||{}).filter(name=>Array.isArray(columns[name])),length=Math.max(0,...names.map(name=>columns[name].length));return Array.from({length},(_,index)=>Object.fromEntries(names.map(name=>[name,columns[name][index]])))}function withTimeout(promise,label,delay=10000){return Promise.race([promise,new Promise((_,reject)=>window.setTimeout(()=>reject(new Error(`Délai dépassé pendant : ${label}.`)),delay))])}
/* La démo publique ne peut jamais s’activer dans une iframe Grist. */
function isDemoMode(){return window.self===window.top&&new URLSearchParams(window.location.search).get("demo")==="1"&&Boolean(window.ACTIONS_DEMO_DATA)}function gristDate(value){return value?Math.floor(new Date(`${value}T00:00:00`).getTime()/1000):null}function nowGrist(){return Math.floor(Date.now()/1000)}function optionalNumber(value){return hasValue(value)?Number(value):null}function startOfToday(){const date=new Date();date.setHours(0,0,0,0);return date.getTime()}function dateValue(value){if(!hasValue(value))return 0;const date=new Date(typeof value==="number"?value*1000:value);return Number.isNaN(date.getTime())?0:date.getTime()}function formatDate(value){const timestamp=dateValue(value);return timestamp?new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"long",year:"numeric"}).format(new Date(timestamp)):""}
function hasValue(value){return value!==null&&value!==undefined&&String(value).trim()!==""}function displayValue(value){if(Array.isArray(value))return value.filter(item=>item!=="L").map(displayValue).join(", ");return hasValue(value)?String(value).trim():""}function textOr(value,fallback){return hasValue(value)?displayValue(value):fallback}function normalizeText(value){return displayValue(value).toLocaleLowerCase("fr-FR").normalize("NFD").replace(/[\u0300-\u036f]/g,"")}function isTrue(value){return value===true||value===1||["true","vrai","oui","1"].includes(normalizeText(value))}function exactError(error){return error instanceof Error?error.message:String(error)}function element(tag,className){const node=document.createElement(tag);if(className)node.className=className;return node}function textElement(tag,value,className){const node=element(tag,className);node.textContent=displayValue(value);return node}
const renderActionsView = render;
render = function renderWithProjectReturn() {
  renderActionsView();
  window.PilotageContext?.configureProjectReturn(document.querySelector("#project-return"), state.project);
};

initialize();
