"use strict";
const TABLE="ACTIONS",REQUIRED_TABLES=["PROJETS",TABLE,"INTERLOCUTEURS"],READ_ONLY_COLUMNS=new Set(["En_retard","A_controler"]);
const STATUS={assign:"À attribuer",todo:"À faire",progress:"En cours",done:"Réalisée",failed:"Non aboutie"};
const state={projects:[],actions:[],people:[],services:[],meetings:[],columns:new Set(),project:null,demo:false,busy:false,includeMeetings:false,includeServices:false,sort:"due"};
const ui={interfaceState:document.querySelector("#interface-state"),content:document.querySelector("#actions-content"),feedback:document.querySelector("#feedback"),selector:document.querySelector("#project-selector"),contextLabel:document.querySelector("#context-label"),contextProject:document.querySelector("#context-project"),sort:document.querySelector("#action-sort"),openCreate:document.querySelector("#open-create"),dialog:document.querySelector("#action-dialog"),form:document.querySelector("#action-form"),summary:document.querySelector("#summary"),sections:Object.fromEntries([...document.querySelectorAll("[data-section]")].map(section=>[section.dataset.section,{list:section.querySelector("[data-list]"),count:section.querySelector("[data-count]")}]))};

async function initialize(){bindControls();try{if(isDemoMode()){state.demo=true;state.includeMeetings=true;state.includeServices=Boolean(window.ACTIONS_DEMO_DATA.tables.SERVICES);applyTables(window.ACTIONS_DEMO_DATA.tables);return}if(!window.grist?.docApi)throw new Error("L’API Grist n’est pas disponible.");await withTimeout(Promise.resolve(window.grist.ready({requiredAccess:"full"})),"initialisation de l’API Grist");const tableNames=normalizeTableNames(await withTimeout(window.grist.docApi.listTables(),"détection des tables")),missing=REQUIRED_TABLES.filter(name=>!tableNames.includes(name));if(missing.length)throw new Error(`Tables Grist introuvables : ${missing.join(", ")}.`);state.includeMeetings=tableNames.includes("REUNIONS");state.includeServices=tableNames.includes("SERVICES");await reloadTables();window.grist.onRecord(record=>{const project=record&&state.projects.find(item=>String(item.id)===String(record.id));if(project){state.project=project;ui.selector.value=String(project.id);render()}})}catch(error){showFatal("Connexion à Grist impossible",exactError(error))}}
async function reloadTables(preferredProjectId=state.project?.id){const names=[...REQUIRED_TABLES,...(state.includeMeetings?["REUNIONS"]:[]),...(state.includeServices?["SERVICES"]:[])],entries=await Promise.all(names.map(async name=>{const raw=await withTimeout(window.grist.docApi.fetchTable(name),`lecture de ${name}`);if(name===TABLE)state.columns=new Set(Object.keys(raw).filter(key=>Array.isArray(raw[key])));return[name,columnarToRecords(raw)]}));applyTables(Object.fromEntries(entries),preferredProjectId)}
function applyTables(tables,preferredProjectId){state.projects=tables.PROJETS||[];state.actions=tables.ACTIONS||[];state.people=tables.INTERLOCUTEURS||[];state.services=tables.SERVICES||[];state.meetings=tables.REUNIONS||[];if(state.demo)state.columns=new Set(Object.keys(state.actions[0]||{}));populateSelectors();state.project=window.PilotageContext?.selectProject(state.projects,preferredProjectId,firstActiveProject)||state.projects.find(item=>String(item.id)===String(preferredProjectId))||firstActiveProject();render()}
function populateSelectors(){const projects=[...state.projects].sort((a,b)=>textOr(a.Nom_projet,"").localeCompare(textOr(b.Nom_projet,""),"fr"));ui.selector.replaceChildren(...projects.map(project=>option(project.id,textOr(project.Nom_projet,"Projet sans nom"))));ui.selector.disabled=!projects.length||Boolean(window.PilotageContext?.isProjectMode);populateServices()}
function populateServices(){const service=ui.form.elements.Service_destinataire;if(!service)return;const selected=service.value;service.replaceChildren(option("","Aucun service"),...state.services.filter(row=>!Object.hasOwn(row,"Actif")||isTrue(row.Actif)).sort((a,b)=>serviceName(a).localeCompare(serviceName(b),"fr")).map(row=>option(row.id,serviceName(row))));service.disabled=!state.includeServices;if([...service.options].some(item=>item.value===selected))service.value=selected}
function personMeta(person){return [person.Fonction,person.Organisme].filter(hasValue).map(displayValue).join(" · ")}
function renderPersonPicker(picker,query=""){const results=picker.querySelector("[data-person-results]"),hidden=picker.querySelector("[type=hidden]"),normalized=normalizeText(query),people=[...state.people].filter(person=>!Object.hasOwn(person,"Actif")||isTrue(person.Actif)).filter(person=>!normalized||normalizeText([personName(person),person.Fonction,person.Organisme].filter(hasValue).join(" ")).includes(normalized)).sort((a,b)=>personName(a).localeCompare(personName(b),"fr")).slice(0,12);results.replaceChildren(...(people.length?people.map(person=>{const button=element("button","person-picker__option");button.type="button";button.setAttribute("role","option");button.append(textElement("strong",personName(person)),textElement("span",personMeta(person)||"Coordonnées professionnelles non renseignées"));button.addEventListener("click",()=>{hidden.value=String(person.id);picker.querySelector("[data-person-search]").value=personName(person);results.hidden=true});return button}):[textElement("p","Aucun interlocuteur trouvé.","person-picker__empty")]));results.hidden=false}
function resetPersonPickers(){document.querySelectorAll("[data-person-picker]").forEach(picker=>{picker.querySelector("[data-person-search]").value="";picker.querySelector("[type=hidden]").value="";picker.querySelector("[data-person-results]").hidden=true})}

function render(){if(!state.project){showFatal("Aucun projet disponible","Ajoutez un projet dans la table PROJETS.");return}ui.selector.value=String(state.project.id);if(ui.contextLabel)ui.contextLabel.textContent=window.PilotageContext?.isProjectMode?"Projet imposé":"Vue globale";if(ui.contextProject)ui.contextProject.textContent=textOr(state.project.Nom_projet,"Projet");const groups={todo:[],progress:[],overdue:[],history:[]};state.actions.filter(row=>referenceIds(row.Projet).includes(String(state.project.id))).forEach(row=>groups[classify(row)].push(row));for(const key of Object.keys(groups))groups[key].sort(compareActions);const empty={todo:"Aucune action à lancer.",progress:"Aucune action en cours.",overdue:"Aucune action en retard.",history:"Aucune action dans l’historique."};Object.keys(groups).forEach(key=>renderGroup(key,groups[key],empty[key]));renderSummary(groups);ui.interfaceState.hidden=true;ui.interfaceState.style.display="none";ui.content.hidden=false;ui.openCreate.disabled=state.busy}
function renderSummary(groups){const entries=[["À faire",groups.todo.length],["En cours",groups.progress.length],["En retard",groups.overdue.length],["Historique",groups.history.length]];ui.summary.replaceChildren(...entries.map(([label,value])=>{const item=element("div","summary__item");item.append(textElement("strong",value,"summary__value"),textElement("span",label,"summary__label"));return item}))}
function renderGroup(key,rows,emptyText){const section=ui.sections[key];section.count.textContent=String(rows.length);section.list.replaceChildren(...(rows.length?rows.map(row=>renderCard(row,key)):[textElement("p",emptyText,"empty-state")]))}
function renderCard(row,group){const failed=normalizeText(row.Statut).includes("non about")||normalizeText(row.Statut).includes("annul"),card=element("article",`card action-card action-card--${group}${failed?" action-card--cancelled":""}`),header=element("header","action-card__header");header.append(textElement("h3",textOr(row.Action,"Action sans intitulé"),"action-card__title"));const badges=element("div","action-card__badges");badges.append(makeBadge(textOr(row.Statut,statusLabel(group)),statusKind(group,row)));if(isTrue(row.En_retard)||group==="overdue")badges.append(makeBadge("En retard","danger"));header.append(badges);card.append(header);const meta=element("dl","action-card__meta");appendOptionalDefinition(meta,"Demandée par",personValue(row.Demandee_par));appendOptionalDefinition(meta,"Attribuée à",personValue(row.Attribuee_a||row.Responsable));appendOptionalDefinition(meta,"Service",serviceValue(row.Service_destinataire));appendOptionalDefinition(meta,"Créée le",formatDate(row.Date_creation));appendOptionalDefinition(meta,"Échéance",formatDate(row.Echeance),group==="overdue"?"is-overdue":"");if(group==="history")appendOptionalDefinition(meta,"Terminée le",formatDate(row.Date_fin||row.Date_realisation));appendOptionalDefinition(meta,"Origine",meetingValue(row.Reunion_origine||row.Reunion||row.Origine_reunion));card.append(meta);const notes=element("div","action-card__notes");if(group==="history"){appendNote(notes,"Résultat",row.Resultat);appendNote(notes,"Raison de non-aboutissement",row.Raison_non_aboutie||(!hasValue(row.Resultat)?row.Commentaire:""))}if(notes.childElementCount)card.append(notes);if(group!=="history")card.append(renderEditor(row,group));return card}
function renderEditor(row){const editor=element("div","action-card__editor"),fields=element("div","inline-fields"),statusWrapper=element("label","form-field");statusWrapper.append(textElement("span","Statut","form-field__label"));const statusSelect=element("select","form-field__control");[STATUS.todo,STATUS.progress].forEach(value=>statusSelect.append(option(value,value)));statusSelect.value=knownEditableStatus(row.Statut);statusWrapper.append(statusSelect);const result=textareaField("Résultat facultatif",row.Resultat,"Décrivez le résultat obtenu…"),reason=textareaField("Raison de non-aboutissement *",row.Raison_non_aboutie,"Expliquez pourquoi l’action n’a pas abouti");result.label.hidden=true;reason.label.hidden=true;fields.append(statusWrapper,result.label,reason.label);editor.append(fields);const actions=element("div","action-card__actions");actions.append(actionButton("Enregistrer","secondary",()=>saveAction(row,statusSelect.value)));const doneButton=actionButton("Réalisée","success",()=>{if(result.label.hidden){result.label.hidden=false;reason.label.hidden=true;doneButton.textContent="Confirmer : réalisée";result.input.focus();return}markDone(row,result.input.value)}),failedButton=actionButton("Non aboutie","danger",()=>{if(reason.label.hidden){reason.label.hidden=false;result.label.hidden=true;failedButton.textContent="Confirmer : non aboutie";reason.input.focus();return}markFailed(row,reason.input.value)});actions.append(doneButton,failedButton);editor.append(actions);return editor}

async function createAction(formData){const assigned=optionalNumber(formData.get("Attribuee_a")),service=optionalNumber(formData.get("Service_destinataire")),fields=writableFields({Projet:Number(state.project.id),Action:formData.get("Action").trim(),Demandee_par:optionalNumber(formData.get("Demandee_par")),Attribuee_a:assigned,Responsable:state.columns.has("Attribuee_a")?undefined:assigned,Service_destinataire:service,Statut:assigned?STATUS.todo:service?STATUS.assign:STATUS.todo,Date_creation:nowGrist(),Echeance:gristDate(formData.get("Echeance"))});requireFields(fields,["Projet","Action"]);await writeAction(["AddRecord",TABLE,null,fields],"Action créée.");ui.form.reset();resetPersonPickers();populateServices();ui.dialog.close()}
async function saveAction(row,status){const fields=writableFields({Statut:status});requireAnyField(fields);await writeAction(["UpdateRecord",TABLE,row.id,fields],"Action mise à jour.")}
async function markDone(row,result){const fields=writableFields({Statut:STATUS.done,Date_fin:nowGrist(),Date_realisation:state.columns.has("Date_fin")?undefined:nowGrist(),Resultat:result.trim()});requireFields(fields,["Statut"]);await writeAction(["UpdateRecord",TABLE,row.id,fields],"Action marquée comme réalisée.")}
async function markFailed(row,reason){const errors=window.PilotageV3Rules?.actionErrors({Statut:STATUS.failed,Raison_non_aboutie:reason.trim()})||[];if(errors.length)throw new Error(errors[0]);const fields=writableFields({Statut:STATUS.failed,Date_fin:nowGrist(),Date_realisation:state.columns.has("Date_fin")?undefined:nowGrist(),Raison_non_aboutie:reason.trim(),Commentaire:state.columns.has("Raison_non_aboutie")?undefined:reason.trim()});requireFields(fields,["Statut"]);await writeAction(["UpdateRecord",TABLE,row.id,fields],"Action classée non aboutie.")}
async function writeAction(action,successMessage){if(state.busy)return;state.busy=true;setInteractiveDisabled(true);try{if(state.demo)applyDemoAction(action);else await withTimeout(window.grist.docApi.applyUserActions([action]),"écriture dans Grist");if(state.demo)render();else await reloadTables(state.project.id);showFeedback(successMessage)}catch(error){showFeedback(`Écriture impossible — ${exactError(error)}`,true)}finally{state.busy=false;setInteractiveDisabled(false)}}
function applyDemoAction([type,,id,fields]){if(type==="AddRecord")state.actions.push({id:Math.max(0,...state.actions.map(row=>Number(row.id)||0))+1,...fields,En_retard:false,A_controler:false});else{const row=state.actions.find(item=>String(item.id)===String(id));Object.assign(row,fields);row.En_retard=computedOverdue(row);row.A_controler=isTrue(row.Controle_requis)&&isDoneLike(row)&&!isTrue(row.Controle_effectue)}}
function bindControls(){ui.selector.addEventListener("change",()=>{state.project=state.projects.find(project=>String(project.id)===ui.selector.value)||null;render()});ui.sort?.addEventListener("change",()=>{state.sort=ui.sort.value;render()});ui.openCreate.addEventListener("click",()=>{ui.form.reset();resetPersonPickers();populateServices();ui.form.elements.Action.value="";ui.dialog.showModal();ui.form.elements.Action.focus()});document.querySelectorAll("[data-person-picker]").forEach(picker=>{const search=picker.querySelector("[data-person-search]"),hidden=picker.querySelector("[type=hidden]");search.addEventListener("focus",()=>renderPersonPicker(picker,search.value));search.addEventListener("input",()=>{hidden.value="";renderPersonPicker(picker,search.value)});search.addEventListener("keydown",event=>{if(event.key==="Escape")picker.querySelector("[data-person-results]").hidden=true})});ui.dialog.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",()=>ui.dialog.close()));ui.dialog.addEventListener("click",event=>{if(event.target===ui.dialog)ui.dialog.close()});ui.form.addEventListener("submit",async event=>{event.preventDefault();if(!ui.form.reportValidity())return;try{await createAction(new FormData(ui.form))}catch(error){showFeedback(exactError(error),true)}})}

function classify(row){if(isHistory(row))return"history";if(isTrue(row.En_retard)||computedOverdue(row))return"overdue";return normalizeText(row.Statut).includes("cours")?"progress":"todo"}
function isHistory(row){const status=normalizeText(row.Statut);return["realisee","terminee","non aboutie","annulee","controlee","validee","archivee"].some(value=>status.includes(value))}
function isDoneLike(row){return Boolean(dateValue(row.Date_realisation))||["realisee","terminee","controle","validee"].some(value=>normalizeText(row.Statut).includes(value))}
function computedOverdue(row){const due=dateValue(row.Echeance);return due>0&&due<startOfToday()&&!isDoneLike(row)}
function writableFields(values){return Object.fromEntries(Object.entries(values).filter(([key,value])=>state.columns.has(key)&&!READ_ONLY_COLUMNS.has(key)&&value!==null&&value!==undefined))}
function requireFields(fields,names){const missing=names.filter(name=>!Object.hasOwn(fields,name));if(missing.length)throw new Error(`Colonnes obligatoires absentes : ${missing.join(", ")}.`)}function requireAnyField(fields){if(!Object.keys(fields).length)throw new Error("Aucune colonne modifiable compatible n’a été trouvée dans ACTIONS.")}
function firstActiveProject(){return state.projects.find(project=>!isTrue(project.Archive)&&!["termine","abandonne"].includes(normalizeText(project.Statut)))||state.projects[0]||null}
function personValue(value){return referenceIds(value).map(id=>personName(state.people.find(person=>String(person.id)===id))||id).join(", ")}function personName(person){return person?textOr(person.Nom_complet||[person.Prenom,person.Nom].filter(hasValue).join(" "),"Interlocuteur sans nom"):""}function serviceName(service){return service?textOr(service.Nom_service||service.Nom,"Service sans nom"):""}function serviceValue(value){return referenceIds(value).map(id=>serviceName(state.services.find(service=>String(service.id)===id))||id).join(", ")}
function meetingValue(value){return referenceIds(value).map(id=>{const meeting=state.meetings.find(item=>String(item.id)===id);return meeting?`${formatDate(meeting.Date_reunion||meeting.Date)} — ${textOr(meeting.Objet,"Réunion")}`:""}).filter(Boolean).join(", ")}function referenceIds(value){const values=Array.isArray(value)?value:[value];return values.filter(item=>item!=="L"&&hasValue(item)&&Number(item)!==0).map(String)}function compareDueDates(a,b){return(dateValue(a.Echeance)||Infinity)-(dateValue(b.Echeance)||Infinity)}function compareActions(a,b){if(state.sort==="created")return dateValue(b.Date_creation)-dateValue(a.Date_creation)||compareDueDates(a,b);return compareDueDates(a,b)}
function statusKind(group,row){return normalizeText(row?.Statut).includes("non about")||normalizeText(row?.Statut).includes("annul")?"danger":group==="history"?"success":group==="overdue"?"danger":"info"}function statusLabel(group){return({todo:STATUS.todo,progress:STATUS.progress,overdue:"En retard",history:"Terminée"})[group]}function knownEditableStatus(value){return normalizeText(value).includes("cours")?STATUS.progress:STATUS.todo}
function textareaField(label,value,placeholder){const wrapper=element("label","form-field");wrapper.append(textElement("span",label,"form-field__label"));const input=element("textarea","form-field__control");input.value=displayValue(value);input.placeholder=placeholder;wrapper.append(input);return{label:wrapper,input}}function appendDefinition(container,label,value,className=""){const wrapper=element("div",className);wrapper.append(textElement("dt",label),textElement("dd",value));container.append(wrapper)}function appendOptionalDefinition(container,label,value,className=""){if(hasValue(value))appendDefinition(container,label,value,className)}function appendNote(container,label,value){if(!hasValue(value))return;const note=element("section","action-card__note");note.append(textElement("strong",label),textElement("p",value));container.append(note)}
function makeBadge(value,kind){return textElement("span",value,`badge badge--${kind}`)}function actionButton(label,kind,handler){const button=textElement("button",label,`button button--${kind}`);button.type="button";button.addEventListener("click",()=>Promise.resolve().then(handler).catch(error=>showFeedback(exactError(error),true)));return button}function option(value,label){const node=element("option");node.value=String(value);node.textContent=label;return node}
function setInteractiveDisabled(disabled){document.querySelectorAll("button, textarea, select, input").forEach(control=>{control.disabled=disabled})}function showFeedback(message,error=false){ui.feedback.textContent=message;ui.feedback.className=`feedback${error?" feedback--error":""}`;ui.feedback.hidden=false;window.setTimeout(()=>{ui.feedback.hidden=true},6000)}function showFatal(title,message){ui.content.hidden=true;ui.interfaceState.replaceChildren(textElement("strong",title),textElement("p",message));ui.interfaceState.style.display="";ui.interfaceState.hidden=false}
function normalizeTableNames(value){const rows=Array.isArray(value)?value:Array.isArray(value?.tables)?value.tables:[];return rows.map(row=>typeof row==="string"?row:row?.id??row?.tableId??row?.name??"").filter(Boolean)}function columnarToRecords(columns){const names=Object.keys(columns||{}).filter(name=>Array.isArray(columns[name])),length=Math.max(0,...names.map(name=>columns[name].length));return Array.from({length},(_,index)=>Object.fromEntries(names.map(name=>[name,columns[name][index]])))}function withTimeout(promise,label,delay=10000){return Promise.race([promise,new Promise((_,reject)=>window.setTimeout(()=>reject(new Error(`Délai dépassé pendant : ${label}.`)),delay))])}
/* La démo publique ne peut jamais s’activer dans une iframe Grist. */
function isDemoMode(){return window.self===window.top&&new URLSearchParams(window.location.search).get("demo")==="1"&&Boolean(window.ACTIONS_DEMO_DATA)}function gristDate(value){return value?Math.floor(new Date(`${value}T00:00:00`).getTime()/1000):null}function nowGrist(){return Math.floor(Date.now()/1000)}function optionalNumber(value){return hasValue(value)?Number(value):null}function startOfToday(){const date=new Date();date.setHours(0,0,0,0);return date.getTime()}function dateValue(value){if(!hasValue(value))return 0;const date=new Date(typeof value==="number"?value*1000:value);return Number.isNaN(date.getTime())?0:date.getTime()}function formatDate(value){const timestamp=dateValue(value);return timestamp?new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"long",year:"numeric"}).format(new Date(timestamp)):""}
function hasValue(value){return value!==null&&value!==undefined&&String(value).trim()!==""}function displayValue(value){if(Array.isArray(value))return value.filter(item=>item!=="L").map(displayValue).join(", ");return hasValue(value)?String(value).trim():""}function textOr(value,fallback){return hasValue(value)?displayValue(value):fallback}function normalizeText(value){return displayValue(value).toLocaleLowerCase("fr-FR").normalize("NFD").replace(/[\u0300-\u036f]/g,"")}function isTrue(value){return value===true||value===1||["true","vrai","oui","1"].includes(normalizeText(value))}function exactError(error){return error instanceof Error?error.message:String(error)}function element(tag,className){const node=document.createElement(tag);if(className)node.className=className;return node}function textElement(tag,value,className){const node=element(tag,className);node.textContent=displayValue(value);return node}
const renderActionsView = render;
render = function renderWithProjectReturn() {
  renderActionsView();
  window.PilotageContext?.configureProjectReturn(document.querySelector("#project-return"), state.project);
};

initialize();
